"""Finite scalar/event fixtures; independent numerical vectors, not interval proofs."""
from mpmath import mp
from orbital import Tick, aggregate, geometry, frontier_events

GRID=2**32
SCALE=10**40

def scalar_fixture(n, raw, keys, radii, boundaries):
    ticks=[Tick(r,None if k is None else mp.mpf(k)/GRID) for k,r in zip(keys,radii)]
    x=[mp.mpf(v)*GRID for v in raw]
    mean=sum(x)/n
    rho=mp.sqrt(sum((v-mean)**2 for v in x))
    radius=sum(mp.mpf(t.radius)*GRID for t in ticks[boundaries:])
    axial=sum(mp.mpf(t.radius)*t.boundary*GRID for t in ticks[:boundaries])
    sigma=sum(mp.mpf(t.radius)*geometry(n,t)['sigma']*GRID for t in ticks[:boundaries])
    normals=[radius-(sum(x)-axial)/n-(rho-sigma)*(v-mean)/rho for v in x]
    # Vector norm avoids copying production's separated axial/transverse squares.
    residual=sum(g*g for g in normals)-radius*radius
    baskets=[]
    for index,tick in enumerate(ticks):
        r=mp.mpf(tick.radius)*GRID
        if index<boundaries:
            baskets.append([r*tick.boundary/n+r*geometry(n,tick)['sigma']*(v-mean)/rho for v in x])
        else:
            baskets.append([r-r*g/radius for g in normals])
    tolerance=mp.power(10,-mp.dps+20)
    assert max(abs(sum(row[i] for row in baskets)-x[i]) for i in range(n)) < tolerance*sum(radii)*GRID
    feasible=True
    for tick,row in zip(ticks,baskets):
        r=mp.mpf(tick.radius)*GRID
        if sum((v-r)**2 for v in row)>r*r*(1+tolerance): feasible=False
        if tick.boundary is not None and sum(row)>r*tick.boundary+tolerance*r: feasible=False
        if any(v<geometry(n,tick)['virtual']*GRID-tolerance*r or v>r+tolerance*r for v in row): feasible=False
    return dict(n=n,x=[str(v) for v in raw],keys=keys,radii=[str(v) for v in radii],boundaries=boundaries,
                normal_floor=[str(int(mp.floor(v))) for v in normals],
                residual_floor=str(int(mp.floor(residual))),feasible=feasible)

def corpus(dps):
    with mp.workdps(dps):
        cases=[]
        for z in (104*SCALE//100,103*SCALE//100):
            cases.append(scalar_fixture(2,[SCALE//4,z],[5*2**29,None],[SCALE,SCALE],1))
        for n,keys,prices in ((3,[13*GRID//10,135*GRID//100,None],[1,3,2]),
                              (8,[21*GRID//4,53*GRID//10,None],list(range(1,9)))):
            radii=[SCALE,2*SCALE,10*SCALE]
            ticks=[Tick(r,None if k is None else mp.mpf(k)/GRID) for k,r in zip(keys,radii)]
            raw=[int(mp.ceil(v))+10**25 for v in aggregate(prices,ticks)]
            cases.append(scalar_fixture(n,raw,keys,radii,2))
        start=[2527133520585472095299795479050357292168,10306468614415789726245162508561985295187]
        events=frontier_events(start,[Tick(SCALE,mp.mpf(5)/8),Tick(SCALE)],0,1,SCALE)
        return dict(scalars=cases,events=[dict(direction=e['direction'],input_floor=str(int(mp.floor(e['input']*GRID))),
                    output_floor=str(int(mp.floor(e['output']*GRID)))) for e in events])

def solidity_source(fixtures):
    lines=['// SPDX-License-Identifier: MIT','pragma solidity 0.8.30;',
           '// Generated by packages/reference/fixtures_curve_primitives.py --write.',
           '// Exact integer floors are stable at 110/160 digits; finite oracle data only.',
           'import {OrbitalMath as M} from "../../src/libraries/OrbitalMath.sol";',
           'import {TickGeometry as G} from "../../src/libraries/TickGeometry.sol";',
           'import {SignedWide as S} from "../../src/libraries/SignedWide.sol";',
           'import {WideMath as W} from "../../src/libraries/WideMath.sol";',
           'library CurvePrimitiveFixtures {',
           'function scalar(uint256 index) internal pure returns(uint8 n,uint256[] memory x,M.Tick[] memory ticks,uint8 boundaries,int256[] memory normals,S.Int512 memory residualFloor,bool feasible){']
    for index,f in enumerate(fixtures['scalars']):
        lines.append(f'if(index=={index}){{')
        lines.extend([f'n={f["n"]};boundaries={f["boundaries"]};',
                      f'x=new uint256[]({f["n"]});normals=new int256[]({f["n"]});'])
        for i,(x,normal) in enumerate(zip(f['x'],f['normal_floor'])):
            lines.append(f'x[{i}]={x};normals[{i}]={normal};')
        lines.append(f'ticks=new M.Tick[]({len(f["keys"])});')
        for i,(key,radius) in enumerate(zip(f['keys'],f['radii'])):
            key='type(uint64).max' if key is None else str(key)
            lines.append(f'ticks[{i}]=M.Tick({key},{radius},G.coefficients(n,{key}));')
        residual=int(f['residual_floor']);magnitude=abs(residual)
        lines.append(f'residualFloor=S.fromParts({str(residual<0).lower()},W.Uint512({magnitude>>256},{magnitude%(2**256)}));')
        lines.append(f'feasible={str(f["feasible"]).lower()};return(n,x,ticks,boundaries,normals,residualFloor,feasible);}}')
    lines.extend(['revert("unknown fixture");','}','}'])
    return '\n'.join(lines)+'\n'

if __name__=='__main__':
    import json
    import sys
    from pathlib import Path
    fixtures=corpus(160)
    assert fixtures==corpus(110)
    encoded=json.dumps(fixtures,indent=2)+'\n'
    if '--write' in sys.argv:
        base=Path(__file__).resolve().parent
        (base/'fixtures').mkdir(exist_ok=True)
        (base/'fixtures/curve-primitives.json').write_text(encoded,encoding='utf-8')
        target=base.parent/'contracts/test/fixtures/CurvePrimitiveFixtures.sol'
        target.parent.mkdir(exist_ok=True)
        target.write_text(solidity_source(fixtures),encoding='utf-8')
        print('Wrote precision-stable JSON and Solidity fixtures.')
    else:
        print(encoded,end='')
