"""Exact lower-sheet proposal oracle using pair differences and integer bisection.

No discriminant, square root, production source, or floating arithmetic is used.
This oracle chooses the largest integer on the lower side of an open variance
gap; a proposal is not a membership, price, root, or connected-path certificate.
"""
from fractions import Fraction
from pathlib import Path


def pair_variance(point):
    return sum((a-b)**2 for i, a in enumerate(point) for b in point[i+1:])


def oracle(point, output, sigma, lower):
    n = len(point)
    assert 2 <= n <= 8 and 0 <= output < n
    assert all(0 <= x < 2**192 for x in point) and 0 <= sigma < 2**192
    assert lower >= 0
    if lower > point[output]:
        return False, None
    untouched = [x for k, x in enumerate(point) if k != output]
    mean = Fraction(sum(untouched), n-1)
    threshold = n*sigma**2

    def variance(z):
        return pair_variance([z, *untouched])

    # The lower half-line is monotone decreasing toward this exact minimum.
    # Equality at the minimum does not establish an open excluded interval.
    if variance(mean) >= threshold or variance(0) < threshold:
        return False, None
    lo, hi = 0, mean.numerator//mean.denominator + 1
    while lo+1 < hi:
        mid = (lo+hi)//2
        if variance(mid) >= threshold:
            lo = mid
        else:
            hi = mid
    assert variance(lo) >= threshold
    assert lo+1 > mean or variance(lo+1) < threshold
    capped = min(point[output], lo)
    return capped >= lower, capped


def cases():
    rows = []
    for n in range(2, 9):
        output = n//2
        small = [10+(k*7+n)%5 for k in range(n)]
        rows.append((f'n{n}-small', small, output, 3, 0))
        for bits in [64, 191]:
            base = 2**bits
            point = [base+(((k*7+n)%5)-2)*(base//64) for k in range(n)]
            rows.append((f'n{n}-varied-{bits}', point, output, base//3, 0))
        base = 2**64
        point = [base+(((k*7+n)%5)-2)*(base//64) for k in range(n)]
        below = point.copy()
        below[output] = 0
        rows.append((f'n{n}-already-below', below, output, base//3, 0))
        rows.append((f'n{n}-caller-lower', point, output, base//3, point[output]))
        rows.append((f'n{n}-spread', [10*(k%2) for k in range(n)], output, 1, 0))
    rows.extend([
        ('exact-sheet-edge', [1, 0, 2, 2], 0, 2, 0),
        ('zero-sigma', [10, 11, 12], 0, 0, 0),
        ('no-nonnegative-side', [10, 0, 0], 0, 3, 0),
        ('lower-above-current', [10, 11, 12], 0, 3, 11),
        ('exact-caller-lower', [10, 11, 12], 0, 3, 7),
    ])
    return rows


def solidity():
    lines = ['// SPDX-License-Identifier: MIT', 'pragma solidity 0.8.30;',
             '// Generated by packages/reference/fixtures_lower_sheet.py; exact pair-difference/bisection oracle.',
             'library LowerSheetFixtures {',
             '    struct Case { uint256[] point; uint8 output; uint256 sigma; uint256 lower; bool found; uint256 ceiling; }',
             f'    uint256 internal constant COUNT = {len(cases())};',
             '    function get(uint256 index) internal pure returns (Case memory c) {']
    for index, (name, point, output, sigma, lower) in enumerate(cases()):
        found, ceiling = oracle(point, output, sigma, lower)
        lines.extend([f'        if (index == {index}) {{ // {name}',
                      f'            c.point = new uint256[]({len(point)});'])
        lines.extend(f'            c.point[{k}] = {x};' for k, x in enumerate(point))
        lines.extend([f'            c.output = {output}; c.sigma = {sigma}; c.lower = {lower};',
                      f'            c.found = {str(found).lower()}; c.ceiling = {ceiling or 0}; return c;', '        }'])
    lines.extend(['        revert("fixture index");', '    }', '}', ''])
    return '\n'.join(lines)


if __name__ == '__main__':
    target = Path(__file__).resolve().parents[1]/'contracts/test/fixtures/LowerSheetFixtures.sol'
    target.write_text(solidity(), encoding='utf-8', newline='\n')
    print(f'Generated {len(cases())} exact finite proposal cases: {target}')
