// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;
import {Test} from "forge-std/Test.sol";
import {OrbitalMath as M} from "../src/libraries/OrbitalMath.sol";
import {TickGeometry as G} from "../src/libraries/TickGeometry.sol";
import {FrontierComposition as C} from "../src/libraries/FrontierComposition.sol";
import {FrontierEndpoint as E} from "../src/libraries/FrontierEndpoint.sol";
import {RootBracket as B} from "../src/libraries/RootBracket.sol";
import {FrontierSchedule as Schedule} from "../src/libraries/FrontierSchedule.sol";
import {CurvePrimitiveFixtures as F} from "./fixtures/CurvePrimitiveFixtures.sol";

contract FrontierCompositionTest is Test {
    uint256 constant SCALE=1e40;uint256 constant GRID=1<<32;uint256 constant U=1<<64;
    function decimals(uint256 n,uint8 d) private pure returns(uint8[] memory result){result=new uint8[](n);for(uint256 i;i<n;i++)result[i]=d;}
    function pair(bool release) private pure returns(uint256[] memory x,M.Tick[] memory ticks){
        x=new uint256[](2);uint64 key;
        if(release){x[0]=15*SCALE/10;x[1]=3*SCALE/10;key=uint64(7*GRID/8);}
        else {x[0]=2527133520585472095299795479050357292168;x[1]=10306468614415789726245162508561985295187;key=uint64(5*GRID/8);}
        ticks=new M.Tick[](2);ticks[0]=M.Tick(key,uint192(SCALE),G.coefficients(2,key));ticks[1]=M.Tick(type(uint64).max,uint192(SCALE),G.coefficients(2,type(uint64).max));
    }
    function accepted(uint256[] memory x,M.Tick[] memory ticks,C.Result memory r,uint8 input,uint8 output,uint8 maxCrossings) private pure {
        assertEq(uint256(r.status),uint256(C.Status.FrontierPathCertified));assertTrue(r.initial.identified);
        assertEq(uint256(r.endpoint.status),uint256(E.Status.EndpointCertified));assertTrue(M.certify(r.endpoint.reserves,ticks));
        assertGt(r.endpoint.amountOutRaw,0);assertLe(r.endpoint.shortfallUpper,r.endpoint.outputQuantum);
        assertEq(r.endpoint.reserves[input],x[input]+r.endpoint.netInputInternal);
        assertEq(r.endpoint.reserves[output],x[output]-r.endpoint.amountOutRaw*r.endpoint.outputQuantum);
        assertEq(uint256(r.refinementUsed)+r.refinementRemaining,160);
        assertEq(r.initial.bracket.used,0);assertEq(uint256(r.refinementUsed),uint256(r.firstSolveUsed)+r.resumeUsed);
        assertEq(r.endpoint.root.bracket.used,r.resumeAttempted?r.resumeUsed:r.firstSolveUsed);
        assertEq(uint256(r.releaseCrossings)+r.frontierCrossings,r.transitions.length);
        assertEq(r.transitions.length+r.crossingRemaining,maxCrossings);
        for(uint256 i;i<x.length;i++)if(i!=input&&i!=output)assertEq(r.endpoint.reserves[i],x[i]);
    }
    /// @dev Independent explicit per-tick support roots, stable at110/160 digits.
    /// Values are regenerated by fixtures_frontier_composition.py. A broad
    /// certified bracket encloses the root; it is not equated to its floor.
    function oracle(C.Result memory r,uint256 index) private pure {
        uint256[9] memory oracleOutputs=[uint256(4126770776962595252),333207013780241401,499288825743866812,333207,427517751760020282527,89372519051296279071,622772057530580375589,157670507261635933550,718010770131401740767];
        uint256[9] memory oracleInitialFloors=[uint256(44500767304604138371755601356080263154504059660318),118110706132445067948266727102904585864375072737707,468195371646119086619158565181678623455543623944581,118110706132445067948266727102904585864375072737707,44265902686493291020235765852479046831669250602168,44265902686493291020235765852479046831669250602168,65524297618767354914979544284572806645934403583794,2727661870432494227584340053151140775347369778220,420668240473326354431375133124432374024542760698234];
        uint256[9] memory oracleFinalFloors=[uint256(44340703412623690595350829985285122856085410428353),118084306753006480165245949185059670947237519748186,468155813909892268425727901700349720754977690259405,118084306753006480165245949185059670947237519748186,10394499721990445534545676125646453187321562926170,37185125172460963803007118235299241097014774485162,17660404034224398411024281327118108402279574998276,392957314968612896686197888493888758032540106903,372180558887437208508708030248254702184192266235154];
        uint256[9] memory oracleShortfalls=[uint256(15883576254408445846),6040614287645789571,4040979190518749037,254200586404224373115595443587,1670660945679732315,3022644431144536079,13322567524036591609,11618802670142378392,15464963850645423154];
        assertEq(r.endpoint.amountOutRaw,oracleOutputs[index]);
        assertLe(r.initial.bracket.lo,oracleInitialFloors[index]);assertGe(r.initial.bracket.hi,oracleInitialFloors[index]+1);
        assertLe(r.endpoint.root.bracket.lo,oracleFinalFloors[index]);assertGe(r.endpoint.root.bracket.hi,oracleFinalFloors[index]+1);
        assertGe(r.endpoint.shortfallUpper,oracleShortfalls[index]);assertLe(r.endpoint.shortfallUpper,r.endpoint.outputQuantum);
    }
    function testOrdinaryMixedTwoTokenPathExecutes() public pure {_ordinary(0);}
    function testOrdinaryMixedThreeTokenPathExecutes() public pure {_ordinary(1);}
    function testOrdinaryMixedEightTokenPathExecutes() public pure {_ordinary(2);}
    function testPayoutTargetAvoidsResumeForOrdinaryMixedPath() public pure {
        (,uint256[] memory x,M.Tick[] memory ticks,,,,)=F.scalar(2);
        C.Result memory r=C.certify(x,ticks,decimals(3,18),0,1,1e18,0);accepted(x,ticks,r,0,1,0);
        assertEq(uint256(r.endpoint.root.bracket.status),uint256(B.Status.PayoutBounded));assertFalse(r.resumeAttempted);
        assertEq(r.resumeUsed,0);assertGt(r.firstSolveUsed,0);assertLt(r.firstSolveUsed,115);oracle(r,1);
    }
    function testFallbackAfterOutwardEventSucceedsWithOneSharedLedger() public pure {
        (uint256[] memory x,M.Tick[] memory ticks)=pair(true);uint256 raw=125744046821095790489;
        uint8[] memory d=decimals(2,18);d[1]=17;
        E.Result memory coarse=E.exactInputForPayout(x,ticks,d,0,1,raw,1,160);
        assertEq(uint256(coarse.status),uint256(E.Status.EndpointCertified));
        Schedule.Result memory schedule=Schedule.enumerate(x,ticks,0,1,raw*U,0,1,1);
        assertEq(uint256(schedule.status),uint256(Schedule.Status.OrderingCertified));assertEq(schedule.events.length,1);
        // Financial precision is sufficient, but final cumulative output does
        // not yet strictly follow the outward event's certified output box.
        assertLe(int256(x[1]*GRID-coarse.root.bracket.hi),schedule.events[0].candidate.outputHi);
        E.Result memory full=E.exactInput(x,ticks,d,0,1,raw,1,160);
        assertEq(uint256(full.status),uint256(E.Status.EndpointCertified));
        assertGt(int256(x[1]*GRID-full.root.bracket.hi),schedule.events[0].candidate.outputHi);
        C.Result memory r=C.certify(x,ticks,d,0,1,raw,2);accepted(x,ticks,r,0,1,2);
        assertTrue(r.resumeAttempted);assertGt(r.resumeUsed,0);assertEq(r.firstSolveUsed,coarse.root.bracket.used);
        assertEq(r.endpoint.amountOutRaw,15284910113323340133);assertEq(r.endpoint.amountOutRaw,full.amountOutRaw);
        assertGe(r.endpoint.root.bracket.lo,coarse.root.bracket.lo);assertLe(r.endpoint.root.bracket.hi,coarse.root.bracket.hi);
        uint256 rootFloor=774948463256958748921205633758743101811279660918;
        assertLe(r.endpoint.root.bracket.lo,rootFloor);assertGe(r.endpoint.root.bracket.hi,rootFloor+1);
        assertGe(r.endpoint.shortfallUpper,149862797252778292187);
        assertTrue(r.transitions[0].inward);assertFalse(r.transitions[1].inward);
    }
    function _ordinary(uint256 k) private pure {
        uint256[3] memory indices=[uint256(0),2,3];uint256[3] memory outputs=[uint256(4126770776962595252),333207013780241401,499288825743866812];
        (uint8 n,uint256[] memory x,M.Tick[] memory ticks,uint8 count,,,)=F.scalar(indices[k]);
        C.Result memory r=C.certify(x,ticks,decimals(n,18),0,1,1e18,0);
        accepted(x,ticks,r,0,1,0);assertEq(r.initial.boundaryCount,count);assertEq(r.endpoint.root.boundaryCount,count);
        assertEq(r.endpoint.amountOutRaw,outputs[k]);assertEq(r.transitions.length,0);
        oracle(r,k);
    }
    function testTwoRootsCrossInwardAndOutwardWithSameFinalPrefix() public pure {
        (uint256[] memory x,M.Tick[] memory ticks)=pair(false);
        C.Result memory r=C.certify(x,ticks,decimals(2,18),0,1,8*SCALE/10/U,2);accepted(x,ticks,r,0,1,2);
        assertEq(r.initial.boundaryCount,1);assertEq(r.endpoint.root.boundaryCount,1);assertEq(r.transitions.length,2);
        assertTrue(r.transitions[0].inward);assertFalse(r.transitions[1].inward);
        for(uint256 i;i<2;i++){assertEq(r.transitions[i].key,ticks[0].key);assertFalse(r.transitions[i].initialRelease);}
        oracle(r,4);
    }
    function testSingleInwardFrontierCrossingUsesExactlyOneAllowance() public pure {
        (uint256[] memory x,M.Tick[] memory ticks)=pair(false);
        C.Result memory r=C.certify(x,ticks,decimals(2,18),0,1,SCALE/10/U,1);accepted(x,ticks,r,0,1,1);
        assertEq(r.endpoint.root.boundaryCount,0);assertEq(r.frontierCrossings,1);assertTrue(r.transitions[0].inward);
        oracle(r,5);
    }
    function testInitialReleaseAndLaterFrontierDirectionsAreReturnedInOrder() public pure {
        (uint256[] memory x,M.Tick[] memory ticks)=pair(true);
        C.Result memory r=C.certify(x,ticks,decimals(2,18),0,1,35*SCALE/100/U,2);accepted(x,ticks,r,0,1,2);
        assertEq(r.initial.boundaryCount,0);assertEq(r.endpoint.root.boundaryCount,1);
        assertEq(r.releaseCrossings,1);assertEq(r.frontierCrossings,1);
        assertTrue(r.transitions[0].initialRelease);assertTrue(r.transitions[0].inward);
        assertFalse(r.transitions[1].initialRelease);assertFalse(r.transitions[1].inward);
        assertEq(r.transitions[0].key,ticks[0].key);assertEq(r.transitions[1].key,ticks[0].key);
        oracle(r,7);
    }
    function testCallerCrossingLimitIncludesInitialRelease() public pure {
        (uint256[] memory x,M.Tick[] memory ticks)=pair(true);
        for(uint8 limit;limit<2;limit++){
            C.Result memory r=C.certify(x,ticks,decimals(2,18),0,1,35*SCALE/100/U,limit);
            assertEq(uint256(r.status),uint256(C.Status.TransitionLimit));assertEq(r.refinementUsed,0);
        }
    }
    function testFourFrontierEventsAreNotReplacedByEndpointEquality() public pure {
        M.Tick[] memory ticks=new M.Tick[](3);uint64 low=uint64(61*GRID/100);uint64 high=uint64(5*GRID/8);
        ticks[0]=M.Tick(low,uint192(SCALE),G.coefficients(2,low));ticks[1]=M.Tick(high,uint192(SCALE),G.coefficients(2,high));ticks[2]=M.Tick(type(uint64).max,uint192(SCALE),G.coefficients(2,type(uint64).max));
        uint256[] memory x=new uint256[](2);x[0]=2*SCALE/5;x[1]=39*SCALE/25;
        C.Result memory r=C.certify(x,ticks,decimals(2,18),0,1,11*SCALE/10/U,4);accepted(x,ticks,r,0,1,4);
        assertEq(r.frontierCrossings,4);uint8[4] memory keys=[uint8(1),0,0,1];
        for(uint256 i;i<4;i++){assertEq(r.transitions[i].key,ticks[keys[i]].key);assertEq(r.transitions[i].inward,i<2);}
        oracle(r,6);
    }
    function testThreeTokenMixedTurnHasNoHiddenLowerCrossing() public pure {
        uint64 key=uint64(13*GRID/10);M.Tick[] memory ticks=new M.Tick[](2);
        ticks[0]=M.Tick(key,uint192(SCALE/100),G.coefficients(3,key));ticks[1]=M.Tick(type(uint64).max,uint192(10*SCALE),G.coefficients(3,type(uint64).max));
        uint256[] memory x=new uint256[](3);x[0]=863*SCALE/100;x[1]=999*SCALE/100;x[2]=SCALE/10;
        C.Result memory r=C.certify(x,ticks,decimals(3,18),0,1,SCALE/U,0);accepted(x,ticks,r,0,1,0);
        assertEq(r.initial.boundaryCount,1);assertEq(r.endpoint.root.boundaryCount,1);
        assertLt(x[0]*GRID,r.initial.bracket.lo);
        assertGt(r.endpoint.reserves[0]*GRID,r.endpoint.root.bracket.hi);
        oracle(r,8);
    }
    function testMixedDecimalsKeepOneFinancialOutputFloor() public pure {
        (uint8 n,uint256[] memory x,M.Tick[] memory ticks,,,,)=F.scalar(2);uint8[] memory d=decimals(n,18);d[0]=6;d[1]=6;
        C.Result memory r=C.certify(x,ticks,d,0,1,1e6,0);accepted(x,ticks,r,0,1,0);
        assertEq(r.endpoint.amountOutRaw,333207);assertEq(r.endpoint.netInputInternal,1e18*U);assertEq(r.endpoint.outputQuantum,1e12*U);
        oracle(r,3);
    }
    function testRoundedCanonicalPrefixHasCertifiedRetentionPhaseAndBudget() public pure {
        uint256 whole=1e18*U;M.Tick[] memory ticks=new M.Tick[](3);
        ticks[0]=M.Tick(uint64(3*GRID/2),uint192(100*whole),G.coefficients(3,uint64(3*GRID/2)));
        ticks[1]=M.Tick(uint64(7*GRID/4),uint192(200*whole),G.coefficients(3,uint64(7*GRID/4)));
        ticks[2]=M.Tick(type(uint64).max,uint192(400*whole),G.coefficients(3,type(uint64).max));
        uint256[] memory x=new uint256[](3);x[0]=500*whole;x[1]=400*whole;x[2]=100*whole;
        C.Result memory r=C.certify(x,ticks,decimals(3,6),0,2,68669858,16);
        assertEq(uint256(r.status),uint256(C.Status.FrontierPathCertified));assertTrue(r.endpoint.root.identified);
        assertEq(r.endpoint.root.boundaryCount,0);assertEq(r.endpoint.actualBoundaryCount,1);
        assertEq(r.endpoint.amountOutRaw,18669858);assertTrue(M.certify(r.endpoint.reserves,ticks));
        assertEq(r.releaseCrossings,0);assertEq(r.frontierCrossings,0);assertEq(r.retentionCrossings,1);
        assertEq(r.transitions.length,1);assertEq(r.crossingRemaining,15);
        assertEq(r.transitions[0].key,ticks[0].key);assertFalse(r.transitions[0].inward);
        assertFalse(r.transitions[0].initialRelease);assertTrue(r.transitions[0].finalRetention);
        assertEq(uint256(r.refinementUsed)+r.refinementRemaining,160);
    }
    function testStrictNegativeAlgebraicEventDoesNotBlockCertifiedSpherePath() public pure {
        uint64 key=uint64(18*GRID/10);M.Tick[] memory ticks=new M.Tick[](2);
        ticks[0]=M.Tick(key,uint192(SCALE),G.coefficients(3,key));ticks[1]=M.Tick(type(uint64).max,uint192(SCALE),G.coefficients(3,type(uint64).max));
        uint256[] memory x=new uint256[](3);x[0]=138*SCALE/100;x[1]=199*SCALE/100;x[2]=SCALE/10;
        assertTrue(M.certify(x,ticks));C.Result memory r=C.certify(x,ticks,decimals(3,18),0,1,SCALE/100/U,16);
        accepted(x,ticks,r,0,1,16);assertEq(r.transitions.length,0);
        assertEq(r.initial.boundaryCount,0);assertEq(r.endpoint.actualBoundaryCount,0);
    }
    function testExactInitialTouchRemainsUncertain() public pure {
        uint64 key=uint64(35*GRID/8);M.Tick[] memory ticks=new M.Tick[](2);
        ticks[0]=M.Tick(key,uint192(8*SCALE),G.coefficients(7,key));ticks[1]=M.Tick(type(uint64).max,uint192(8*SCALE),G.coefficients(7,type(uint64).max));
        uint256[] memory x=new uint256[](7);x[0]=11*SCALE;x[1]=11*SCALE;x[2]=10*SCALE;x[3]=10*SCALE;x[4]=10*SCALE;x[5]=9*SCALE;x[6]=9*SCALE;
        C.Result memory r=C.certify(x,ticks,decimals(7,18),0,1,SCALE/1000/U,16);
        assertEq(uint256(r.status),uint256(C.Status.Uncertain));
    }
    function testCertifiedFinalEndpointCannotBypassUncertainInitialOutputOrder() public pure {
        (uint256[] memory x,M.Tick[] memory ticks)=pair(true);
        C.Result memory r=C.certify(x,ticks,decimals(2,18),0,1,SCALE/100/U,1);
        assertTrue(r.initial.identified);assertEq(uint256(r.endpoint.status),uint256(E.Status.EndpointCertified));
        assertEq(uint256(r.status),uint256(C.Status.Uncertain));assertEq(r.transitions.length,0);
        assertGe(x[1]*GRID-r.initial.bracket.lo,x[1]*GRID-r.endpoint.root.bracket.hi);
        assertEq(uint256(r.refinementUsed)+r.refinementRemaining,160);
    }
    function testZeroInitialOutputNormalNeedsASeparateOneSidedRule() public pure {
        M.Tick[] memory ticks=new M.Tick[](1);ticks[0]=M.Tick(type(uint64).max,uint192(SCALE),G.coefficients(2,type(uint64).max));
        uint256[] memory x=new uint256[](2);x[1]=SCALE;assertTrue(M.certify(x,ticks));
        C.Result memory r=C.certify(x,ticks,decimals(2,18),0,1,SCALE/100/U,0);
        assertEq(uint256(r.status),uint256(C.Status.Uncertain));assertFalse(r.initial.identified);assertEq(r.refinementUsed,0);
    }
    function testActualCallerVectorAndTicksAreUnmodified() public pure {
        (uint256[] memory x,M.Tick[] memory ticks)=pair(false);bytes32 before=keccak256(abi.encode(x,ticks));
        C.Result memory r=C.certify(x,ticks,decimals(2,18),0,1,8*SCALE/10/U,2);accepted(x,ticks,r,0,1,2);
        assertEq(keccak256(abi.encode(x,ticks)),before);
    }
    function testUncertifiedStartDoesNotBecomeGlobalInfeasibility() public pure {
        (uint256[] memory x,M.Tick[] memory ticks)=pair(false);x[0]=0;x[1]=0;
        C.Result memory r=C.certify(x,ticks,decimals(2,18),0,1,1,16);assertEq(uint256(r.status),uint256(C.Status.UncertifiedStart));assertEq(r.refinementUsed,0);
    }
    function call(uint256[] memory x,M.Tick[] memory t,uint8[] memory d,uint8 i,uint8 j,uint256 raw,uint8 bound) external pure {C.certify(x,t,d,i,j,raw,bound);}
    function testInvalidMetadataPairCapacityAndCallerLimitReject() public {
        (uint256[] memory x,M.Tick[] memory ticks)=pair(false);uint8[] memory d=decimals(2,18);
        vm.expectRevert(C.InvalidPair.selector);this.call(x,ticks,d,0,0,1,16);
        vm.expectRevert(C.InvalidInput.selector);this.call(x,ticks,d,0,1,0,16);
        vm.expectRevert(C.InvalidInput.selector);this.call(x,ticks,d,0,1,type(uint256).max,16);
        vm.expectRevert(C.InvalidBound.selector);this.call(x,ticks,d,0,1,1,17);
        d[0]=19;vm.expectRevert(C.InvalidMetadata.selector);this.call(x,ticks,d,0,1,1,16);
    }
}
