import {writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {resolve,dirname} from 'node:path';
import {keccak256,toHex} from 'viem';
import {readVerifiedArtifact} from './artifact-integrity.mjs';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../..');
const contracts=resolve(root,'packages/contracts');
const targets=[
 ['routerAbi','ISwapVM','vendor/swap-vm-orbital/src/interfaces/ISwapVM.sol',['quote','swap']],
 ['lifecycleAbi','IOrbitalLifecycle','src/interfaces/IOrbitalLifecycle.sol',['activateStrategy','retireStrategy','nextMakerNonce','getStrategyConfig','getStrategyState','getStrategyAvailability']],
 ['aquaAbi','IAqua','vendor/aqua/src/interfaces/IAqua.sol',['ship','dock']],
 ['paymentsAbi','OrbitalPayments','src/OrbitalPayments.sol',['createInvoice','cancelInvoice','payWithUSDC','payWithSwap']],
 ['paymentsReadAbi','OrbitalPayments','src/OrbitalPayments.sol',['getInvoice','USDC','ROUTER','allowedToken','nextMerchantNonce']],
 ['lifecycleEventsAbi','IOrbitalLifecycle','src/interfaces/IOrbitalLifecycle.sol',['StrategyActivated','StrategyRetired'],'event'],
 ['paymentsEventsAbi','OrbitalPayments','src/OrbitalPayments.sol',['InvoiceCreated','InvoicePaid','InvoiceCancelled'],'event'],
 ['swapEventsAbi','IOrbitalLifecycle','src/interfaces/IOrbitalLifecycle.sol',['OrbitalSwapExecuted'],'event'],
 ['demoTokenAbi','OrbitalDemoDollar','src/OrbitalDemoDollar.sol',['faucet','nextMintAt','FAUCET_AMOUNT','COOLDOWN','CHAIN_ID']]
];
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const artifactIntegrity=new Map();
async function readArtifact(name,source){
 const result=await readVerifiedArtifact(contracts,name,source);
 const key=`${source}:${name}`,prior=artifactIntegrity.get(key);
 if(prior&&prior.artifactSha256!==result.integrity.artifactSha256)throw Error(`ARTIFACT_CHANGED_DURING_GENERATION: ${key}`);
 artifactIntegrity.set(key,result.integrity);
 return result;
}
const canonicalType=input=>input.type.startsWith('tuple')?`(${input.components.map(canonicalType).join(',')})${input.type.slice(5)}`:input.type;
const provenance=[],eventsProvenance=[],swapEventsProvenance=[],demoTokenProvenance=[];let output='// Generated by scripts/generate-abi.mjs from the pinned Foundry build. Do not edit.\n';
for(const [exportName,name,source,names,type='function'] of targets){
 const {artifact,metadata,bytes,artifactBytes}=await readArtifact(name,source);
 const abi=artifact.abi.filter(item=>item.type===type&&names.includes(item.name));
 if(abi.length!==names.length||names.some(name=>abi.filter(item=>item.name===name).length!==1))throw Error(`Missing or overloaded ABI ${type} in ${name}`);
 let implementation;
 if(exportName==='lifecycleAbi'||exportName==='lifecycleEventsAbi'||exportName==='swapEventsAbi'){
  // Pin the stable interface, and also prove these entries are implemented by
  // the concrete router build. Parameter internalType labels may differ only
  // if Solidity reports aliases; executable input/output types must agree.
  const routerSource='src/OrbitalSwapVMRouter.sol';
  const router=await readArtifact('OrbitalSwapVMRouter',routerSource);
  const executable=item=>JSON.stringify(item, (key,value)=>key==='internalType'?undefined:value);
  for(const entry of abi){
   const implemented=router.artifact.abi.find(item=>item.type===type&&item.name===entry.name);
   if(!implemented||executable(implemented)!==executable(entry))throw Error(`Lifecycle ABI differs from the concrete router: ${entry.name}`);
  }
  implementation={source:`packages/contracts/${routerSource}`,sourceSha256:sha(router.bytes),artifactSha256:sha(router.artifactBytes)};
 }
 output+=`export const ${exportName}=${JSON.stringify(abi,null,2)} as const;\n`;
 const record={exportName,source:`packages/contracts/${source}`,sourceSha256:sha(bytes),compiler:metadata.compiler.version,evmVersion:metadata.settings.evmVersion,optimizerRuns:700,viaIR:true};
 if(type==='function')record.methodIdentifiers=Object.fromEntries(Object.entries(artifact.methodIdentifiers).filter(([signature])=>names.includes(signature.split('(')[0])));
 else{
  record.abiSha256=sha(JSON.stringify(abi));record.artifactSha256=sha(artifactBytes);
  record.eventTopics=Object.fromEntries(abi.map(event=>{
   if(event.anonymous)throw Error(`Anonymous event unsupported: ${event.name}`);
   const signature=`${event.name}(${event.inputs.map(canonicalType).join(',')})`;
   return [signature,keccak256(toHex(signature))];
  }));
  if(implementation)record.implementation=implementation;
 }
 (exportName==='demoTokenAbi'?demoTokenProvenance:type==='function'?provenance:exportName==='swapEventsAbi'?swapEventsProvenance:eventsProvenance).push(record);
}
await mkdir(resolve(root,'packages/sdk/src/generated'),{recursive:true});
await writeFile(resolve(root,'packages/sdk/src/generated/abi.ts'),output);
await writeFile(resolve(root,'packages/sdk/src/generated/provenance.json'),JSON.stringify(provenance,null,2)+'\n');
await writeFile(resolve(root,'packages/sdk/src/generated/events-provenance.json'),JSON.stringify(eventsProvenance,null,2)+'\n');
await writeFile(resolve(root,'packages/sdk/src/generated/swap-events-provenance.json'),JSON.stringify(swapEventsProvenance,null,2)+'\n');
await writeFile(resolve(root,'packages/sdk/src/generated/demo-token-provenance.json'),JSON.stringify(demoTokenProvenance,null,2)+'\n');
await writeFile(resolve(root,'packages/sdk/src/generated/artifact-integrity.json'),JSON.stringify({schemaVersion:1,
 scope:'Local unlinked build source and metadata consistency; not deployment verification.',
 artifacts:[...artifactIntegrity.entries()].sort(([a],[b])=>a<b?-1:a>b?1:0).map(([identity,integrity])=>({identity,...integrity})),
},null,2)+'\n');
