import {test,expect,type Page} from '@playwright/test';
import {setupSwap as setup} from './fixtures/swap';
async function review(page:Page){await expect(page.getByLabel('Quoted output',{exact:true})).toHaveText('20 oUSD18');await page.getByRole('button',{name:'Review swap',exact:true}).click();}
test('standalone approval and fresh swap review lead to exact receipt amounts and crossings',async({page})=>{
 const f=await setup(page);await review(page);await expect(page.getByRole('heading',{name:'Review token approval'})).toBeVisible();await page.getByRole('button',{name:'Approve 9007199254.740993 USDC',exact:true}).click();await expect(page.getByRole('heading',{name:'Approval confirmed',exact:true})).toBeVisible();expect(f.sent.size).toBe(1);
 await page.getByRole('button',{name:'Review fresh swap',exact:true}).click();await expect(page.getByRole('heading',{name:'Review swap',exact:true})).toBeVisible();expect(f.quotes()).toBe(3);
 await page.setViewportSize({width:320,height:760});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'../../test/evidence/swap-review-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Submit reviewed swap',exact:true}).click();await expect(page.getByRole('heading',{name:'Swap complete',exact:true})).toBeVisible();await expect(page.getByText('20.000000000000000007 oUSD18',{exact:true})).toBeVisible();await page.getByText('View transaction receipt',{exact:true}).click();await expect(page.getByText(/Inward · tick/)).toBeVisible();expect(f.sent.size).toBe(2);
 await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'../../test/evidence/swap-receipt-desktop.png',fullPage:true});
});
test('standalone swap rejects insufficient native inventory before requesting any signature',async({page})=>{const f=await setup(page,{approved:true,gasPoor:true});await review(page);await expect(page.getByText(/Insufficient balance for gas/)).toBeVisible();expect(f.sent.size).toBe(0);});
test('docked strategies cannot enter swap review',async({page})=>{const f=await setup(page,{approved:true,docked:true});await review(page);await expect(page.getByText(/strategy is docked/)).toBeVisible();expect(f.sent.size).toBe(0);});
test('changed-version strategies cannot enter swap review',async({page})=>{const f=await setup(page,{approved:true,changed:true});await review(page);await expect(page.getByText('Strategy changed. Refresh the quote.',{exact:true})).toBeVisible();expect(f.sent.size).toBe(0);});
test('standalone signature rejection returns an editable amount without a saved hash',async({page})=>{const f=await setup(page,{approved:true,rejected:true});await review(page);await page.getByRole('button',{name:'Submit reviewed swap'}).click();await expect(page.getByText(/User rejected/)).toBeVisible();await expect(page.getByLabel('You pay',{exact:true})).toHaveValue('9007199254.740993');expect(f.sent.size).toBe(0);});
test('success without an Orbital settlement event stays unresolved',async({page})=>{const f=await setup(page,{approved:true,noEvent:true});await review(page);await page.getByRole('button',{name:'Submit reviewed swap'}).click();await expect(page.getByText(/does not establish the reviewed swap settlement/)).toBeVisible();await expect(page.getByRole('heading',{name:'Swap complete',exact:true})).toHaveCount(0);expect(f.sent.size).toBe(1);});
test('standalone swap resumes a saved receipt after reload without signing again',async({page})=>{
 const f=await setup(page,{approved:true,pending:true});await review(page);await page.getByRole('button',{name:'Submit reviewed swap'}).click();await expect(page.getByRole('button',{name:'Resume swap receipt'})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Manage connected wallet'})).toBeVisible();await expect(page.getByRole('button',{name:'Resume swap receipt'})).toBeVisible();f.ready();await page.getByRole('button',{name:'Resume swap receipt'}).click();await expect(page.getByRole('heading',{name:'Swap complete',exact:true})).toBeVisible();expect(f.sent.size).toBe(1);
});
test('expired swap review cannot request a signature',async({page})=>{
 const f=await setup(page,{approved:true});await review(page);await expect(page.getByRole('button',{name:'Submit reviewed swap'})).toBeVisible();await page.clock.fastForward(61000);await expect(page.getByText('Swap review expired. Get a fresh quote before signing.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Submit reviewed swap'})).toHaveCount(0);expect(f.sent.size).toBe(0);
});
test('switching accounts away and back permanently invalidates the swap review',async({page})=>{
 const f=await setup(page,{approved:true});await review(page);await expect(page.getByRole('button',{name:'Submit reviewed swap'})).toBeVisible();
 await page.evaluate(()=>(window as any).swapExecutionWallet.account('0x0000000000000000000000000000000000000032'));await expect(page.getByRole('button',{name:'Submit reviewed swap'})).toHaveCount(0);
 await page.evaluate(address=>(window as any).swapExecutionWallet.account(address),f.f.request.wallet);await expect(page.getByRole('button',{name:'Review swap',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Submit reviewed swap'})).toHaveCount(0);expect(f.sent.size).toBe(0);
});
test('reverted swap receipts retain gas evidence without claiming settlement',async({page})=>{
 const f=await setup(page,{approved:true,reverted:true});await review(page);await page.getByRole('button',{name:'Submit reviewed swap'}).click();await expect(page.getByRole('heading',{name:'Transaction reverted',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Swap complete',exact:true})).toHaveCount(0);await expect(page.getByText('Actual output',{exact:true})).toHaveCount(0);expect(f.sent.size).toBe(1);
});
test('corrupted approval recovery blocks a new signature after reload',async({page})=>{
 const f=await setup(page,{pending:true});await review(page);await page.getByRole('button',{name:'Approve 9007199254.740993 USDC',exact:true}).click();await expect(page.getByRole('button',{name:'Resume swap receipt'})).toBeVisible();
 await page.evaluate(()=>{const key=Object.keys(localStorage).find(k=>k.startsWith('orbital:swap:1:'))!;const saved=JSON.parse(localStorage.getItem(key)!);saved.plan.to=saved.tokenOut.address;localStorage.setItem(key,JSON.stringify(saved));});await page.reload();await expect(page.getByText('Saved swap recovery could not be read. Check previous wallet activity before retrying.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Resume swap receipt'})).toHaveCount(0);expect(f.sent.size).toBe(1);
});
