"""Bind the named expensive cases to the retained independent 110/160-digit pilot."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'packages/contracts/test/fixtures/PilotGasFixtures.sol'


def checked_witnesses():
    record = json.loads((ROOT / 'test/evidence/mixed-pilot/generation.json').read_text(encoding='utf-8'))
    assert record['exit_status'] == 0 and record['changed_inputs'] == []
    for path, digest in record['inputs'].items():
        assert hashlib.sha256((ROOT / path).read_bytes()).hexdigest() == digest, path
    fixture = ROOT / record['output']['path']
    assert hashlib.sha256(fixture.read_bytes()).hexdigest() == record['output']['sha256']
    data = json.loads(fixture.read_text(encoding='utf-8'))
    configuration = next(c for c in data['configurations'] if c['id'] == 'n8-t8-concentrated')
    selected = configuration['actions'][1:4]
    assert [a['step'] for a in selected] == [1, 2, 3]
    assert all(a['status'] == 'generated' for a in selected)
    return [a['witness'] for a in selected]


def render():
    rows = ['// SPDX-License-Identifier: MIT', 'pragma solidity 0.8.30;',
            '// Generated by scripts/generate-pilot-gas-fixtures.py; do not hand-edit.',
            'import {OrbitalMath as M} from "../../src/libraries/OrbitalMath.sol";',
            'import {TickGeometry as G} from "../../src/libraries/TickGeometry.sol";',
            'library PilotGasFixtures {',
            '    struct Case {uint256[] x;M.Tick[] ticks;uint8[] decimals;uint8 input;uint8 output;uint256 raw;',
            '        uint256 expectedOut;uint256[] expectedReserves;uint8 originalPrefix;uint8 initialPrefix;uint8 finalPrefix;',
            '        uint64[] transitionKeys;bool[] transitionInward;}',
            '    function get(uint8 step) internal pure returns(Case memory c) {',
            '        require(step>=1&&step<=3,"fixture step");',
            '        c.x=new uint256[](8);c.ticks=new M.Tick[](8);c.decimals=new uint8[](8);c.expectedReserves=new uint256[](8);']
    for step, w in enumerate(checked_witnesses(), 1):
        assert w['dimension'] == 8 and len(w['keys']) == 8
        rows += [f'        if(step=={step}) {{ // {w["id"]}',
                 f'            c.input={w["input"]};c.output={w["output"]};c.raw={w["raw_net_input"]};c.expectedOut={w["output_raw"]};',
                 f'            c.originalPrefix={w["actual_initial_prefix"]};c.initialPrefix={w["initial_ideal_prefix"]};c.finalPrefix={w["final_ideal_prefix"]};']
        for k in range(8):
            key = str(w['keys'][k]) if w['keys'][k] is not None else 'type(uint64).max'
            rows += [f'            c.x[{k}]={w["start"][k]};c.expectedReserves[{k}]={w["actual_endpoint"][k]};c.decimals[{k}]={w["decimals"][k]};',
                     f'            c.ticks[{k}]=M.Tick({key},{w["radii"][k]},G.coefficients(8,{key}));']
        rows += [f'            c.transitionKeys=new uint64[]({len(w["transitions"])});c.transitionInward=new bool[]({len(w["transitions"])});']
        for k, event in enumerate(w['transitions']):
            assert not event['initial_release'] and not event['final_retention']
            rows += [f'            c.transitionKeys[{k}]={event["key"]};c.transitionInward[{k}]={str(event["direction"] == "inward").lower()};']
        rows += ['        }']
    return '\n'.join(rows + ['    }', '}', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    expected = render().encode('utf-8')
    if args.write:
        OUTPUT.write_bytes(expected)
    else:
        assert OUTPUT.read_bytes() == expected, 'generated fixture differs'
    print('Three gas fixtures match the authenticated independent pilot.')
