// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;
// Generated by packages/reference/fixtures_initializer.py --write.
// Independent 110/160-digit oracle enclosures; no production geometry import.
import {OrbitalConfigV1} from "../../src/interfaces/IOrbitalRouter.sol";
library InitializerOracleFixtures {
uint256 internal constant COUNT = 12;
struct Expected {
uint256 coordinate;
uint256 virtual_floor;
uint256 virtual_ceil;
uint256 virtual_lower;
uint256 virtual_error_bound;
uint256 principal_lower;
uint256 principal_upper;
uint256 paper_principal_floor;
uint256 coordinate_error_bound;
uint256 principal_error_bound;
uint256 radial_slack_ceil;
uint256 stored_slack_bound;
}
function get(uint256 index) internal pure returns (OrbitalConfigV1 memory c, Expected memory expected) {
c.schemaVersion=1; c.chainId=31337; c.router=address(0x1111); c.maker=address(0x2222); c.feePpm=500;
if(index==0){ // demo-three
c.tokens=new address[](3); c.decimals=new uint8[](3); c.initialAmountsRaw=new uint256[](3);
c.tickKeys=new uint64[](3); c.radiiInternal=new uint192[](3);
c.tokens[0]=address(1); c.decimals[0]=6; c.initialAmountsRaw[0]=3474175;
c.tokens[1]=address(2); c.decimals[1]=18; c.initialAmountsRaw[1]=3474174944466274204;
c.tokens[2]=address(3); c.decimals[2]=6; c.initialAmountsRaw[2]=3474175;
c.tickKeys[0]=6442450944; c.radiiInternal[0]=55340232221128654848000000000000000000;
c.tickKeys[1]=7516192768; c.radiiInternal[1]=55340232221128654848000000000000000000;
c.tickKeys[2]=18446744073709551615; c.radiiInternal[2]=55340232221128654848000000000000000000;
expected.coordinate=70168602753730873934561088066218727386;
expected.virtual_floor=6081386685867419680655147096247855485;
expected.virtual_ceil=6081386685867419680655147096247855486;
expected.virtual_lower=6081386685867419680655147096247855482;
expected.virtual_error_bound=4;
expected.principal_lower=64087216067863454253905940969970871901;
expected.principal_upper=64087216067863454253905940969970871904;
expected.paper_principal_floor=64087216067863454253905940969970871900;
expected.coordinate_error_bound=1;
expected.principal_error_bound=5;
expected.radial_slack_ceil=2;
expected.stored_slack_bound=4;
return (c, expected);
}
if(index==1){ // unequal-radii
c.tokens=new address[](3); c.decimals=new uint8[](3); c.initialAmountsRaw=new uint256[](3);
c.tickKeys=new uint64[](3); c.radiiInternal=new uint192[](3);
c.tokens[0]=address(1); c.decimals[0]=6; c.initialAmountsRaw[0]=1691004;
c.tokens[1]=address(2); c.decimals[1]=18; c.initialAmountsRaw[1]=1691003764702255697;
c.tokens[2]=address(3); c.decimals[2]=8; c.initialAmountsRaw[2]=169100377;
c.tickKeys[0]=6442450944; c.radiiInternal[0]=18446744073709551616000000000001;
c.tickKeys[1]=7516192768; c.radiiInternal[1]=18446744073709551616000000000000003;
c.tickKeys[2]=18446744073709551615; c.radiiInternal[2]=73786976294838206464000000000000000017;
expected.coordinate=31193849976253331149228094212669910508;
expected.virtual_floor=336301111454823292672882191519770;
expected.virtual_ceil=336301111454823292672882191519771;
expected.virtual_lower=336301111454823292672882191519768;
expected.virtual_error_bound=3;
expected.principal_lower=31193513675141876325935421330478390738;
expected.principal_upper=31193513675141876325935421330478390740;
expected.paper_principal_floor=31193513675141876325935421330478390736;
expected.coordinate_error_bound=1;
expected.principal_error_bound=4;
expected.radial_slack_ceil=1;
expected.stored_slack_bound=2;
return (c, expected);
}
if(index==2){ // two-full
c.tokens=new address[](2); c.decimals=new uint8[](2); c.initialAmountsRaw=new uint256[](2);
c.tickKeys=new uint64[](1); c.radiiInternal=new uint192[](1);
c.tokens[0]=address(1); c.decimals[0]=6; c.initialAmountsRaw[0]=1171573;
c.tokens[1]=address(2); c.decimals[1]=18; c.initialAmountsRaw[1]=1171572875253809903;
c.tickKeys[0]=18446744073709551615; c.radiiInternal[0]=73786976294838206464000000000000000000;
expected.coordinate=21611704993507077614601712774989966525;
expected.virtual_floor=0;
expected.virtual_ceil=0;
expected.virtual_lower=0;
expected.virtual_error_bound=0;
expected.principal_lower=21611704993507077614601712774989966525;
expected.principal_upper=21611704993507077614601712774989966525;
expected.paper_principal_floor=21611704993507077614601712774989966524;
expected.coordinate_error_bound=1;
expected.principal_error_bound=1;
expected.radial_slack_ceil=1;
expected.stored_slack_bound=2;
return (c, expected);
}
if(index==3){ // rational-four-full
c.tokens=new address[](4); c.decimals=new uint8[](4); c.initialAmountsRaw=new uint256[](4);
c.tickKeys=new uint64[](1); c.radiiInternal=new uint192[](1);
c.tokens[0]=address(1); c.decimals[0]=0; c.initialAmountsRaw[0]=3;
c.tokens[1]=address(2); c.decimals[1]=6; c.initialAmountsRaw[1]=2000001;
c.tokens[2]=address(3); c.decimals[2]=8; c.initialAmountsRaw[2]=200000001;
c.tokens[3]=address(4); c.decimals[3]=18; c.initialAmountsRaw[3]=2000000000000000001;
c.tickKeys[0]=18446744073709551615; c.radiiInternal[0]=73786976294838206464000000000000000002;
expected.coordinate=36893488147419103232000000000000000001;
expected.virtual_floor=0;
expected.virtual_ceil=0;
expected.virtual_lower=0;
expected.virtual_error_bound=0;
expected.principal_lower=36893488147419103232000000000000000001;
expected.principal_upper=36893488147419103232000000000000000001;
expected.paper_principal_floor=36893488147419103232000000000000000001;
expected.coordinate_error_bound=0;
expected.principal_error_bound=0;
expected.radial_slack_ceil=0;
expected.stored_slack_bound=0;
return (c, expected);
}
if(index==4){ // minimum-width-three
c.tokens=new address[](3); c.decimals=new uint8[](3); c.initialAmountsRaw=new uint256[](3);
c.tickKeys=new uint64[](3); c.radiiInternal=new uint192[](3);
c.tokens[0]=address(1); c.decimals[0]=6; c.initialAmountsRaw[0]=2481531;
c.tokens[1]=address(2); c.decimals[1]=18; c.initialAmountsRaw[1]=2481530376146085610;
c.tokens[2]=address(3); c.decimals[2]=6; c.initialAmountsRaw[2]=2481531;
c.tickKeys[0]=5445800316; c.radiiInternal[0]=55340232221128654848000000000000000000;
c.tickKeys[1]=7516192768; c.radiiInternal[1]=55340232221128654848000000000000000000;
c.tickKeys[2]=18446744073709551615; c.radiiInternal[2]=55340232221128654848000000000000000000;
expected.coordinate=70168602753730873934561088066218727386;
expected.virtual_floor=24392446993827834743895203206408223552;
expected.virtual_ceil=24392446993827834743895203206408223553;
expected.virtual_lower=24392446993827834743895203206408223549;
expected.virtual_error_bound=4;
expected.principal_lower=45776155759903039190665884859810503834;
expected.principal_upper=45776155759903039190665884859810503837;
expected.paper_principal_floor=45776155759903039190665884859810503832;
expected.coordinate_error_bound=1;
expected.principal_error_bound=5;
expected.radial_slack_ceil=2;
expected.stored_slack_bound=4;
return (c, expected);
}
if(index==5){ // eight-ticks-3
c.tokens=new address[](3); c.decimals=new uint8[](3); c.initialAmountsRaw=new uint256[](3);
c.tickKeys=new uint64[](8); c.radiiInternal=new uint192[](8);
c.tokens[0]=address(1); c.decimals[0]=6; c.initialAmountsRaw[0]=15126218;
c.tokens[1]=address(2); c.decimals[1]=18; c.initialAmountsRaw[1]=15126217823068127370;
c.tokens[2]=address(3); c.decimals[2]=0; c.initialAmountsRaw[2]=16;
c.tickKeys[0]=7650410496; c.radiiInternal[0]=18446744073709551616000000000000000000;
c.tickKeys[1]=7784628224; c.radiiInternal[1]=36893488147419103232000000000000000001;
c.tickKeys[2]=7918845952; c.radiiInternal[2]=55340232221128654848000000000000000002;
c.tickKeys[3]=8053063680; c.radiiInternal[3]=73786976294838206464000000000000000003;
c.tickKeys[4]=8187281408; c.radiiInternal[4]=92233720368547758080000000000000000004;
c.tickKeys[5]=8321499136; c.radiiInternal[5]=110680464442257309696000000000000000005;
c.tickKeys[6]=8455716864; c.radiiInternal[6]=129127208515966861312000000000000000006;
c.tickKeys[7]=18446744073709551615; c.radiiInternal[7]=147573952589676412928000000000000000007;
expected.coordinate=280674411014923495738244352264874909554;
expected.virtual_floor=1644942029601722203923547202083454950;
expected.virtual_ceil=1644942029601722203923547202083454951;
expected.virtual_lower=1644942029601722203923547202083454937;
expected.virtual_error_bound=14;
expected.principal_lower=279029468985321773534320805062791454604;
expected.principal_upper=279029468985321773534320805062791454617;
expected.paper_principal_floor=279029468985321773534320805062791454602;
expected.coordinate_error_bound=1;
expected.principal_error_bound=15;
expected.radial_slack_ceil=2;
expected.stored_slack_bound=6;
return (c, expected);
}
if(index==6){ // eight-ticks-5
c.tokens=new address[](5); c.decimals=new uint8[](5); c.initialAmountsRaw=new uint256[](5);
c.tickKeys=new uint64[](8); c.radiiInternal=new uint192[](8);
c.tokens[0]=address(1); c.decimals[0]=6; c.initialAmountsRaw[0]=19857618;
c.tokens[1]=address(2); c.decimals[1]=18; c.initialAmountsRaw[1]=19857617322177034379;
c.tokens[2]=address(3); c.decimals[2]=0; c.initialAmountsRaw[2]=20;
c.tokens[3]=address(4); c.decimals[3]=8; c.initialAmountsRaw[3]=1985761733;
c.tokens[4]=address(5); c.decimals[4]=6; c.initialAmountsRaw[4]=19857618;
c.tickKeys[0]=16240345088; c.radiiInternal[0]=18446744073709551616000000000000000000;
c.tickKeys[1]=16374562816; c.radiiInternal[1]=36893488147419103232000000000000000001;
c.tickKeys[2]=16508780544; c.radiiInternal[2]=55340232221128654848000000000000000002;
c.tickKeys[3]=16642998272; c.radiiInternal[3]=73786976294838206464000000000000000003;
c.tickKeys[4]=16777216000; c.radiiInternal[4]=92233720368547758080000000000000000004;
c.tickKeys[5]=16911433728; c.radiiInternal[5]=110680464442257309696000000000000000005;
c.tickKeys[6]=17045651456; c.radiiInternal[6]=129127208515966861312000000000000000006;
c.tickKeys[7]=18446744073709551615; c.radiiInternal[7]=147573952589676412928000000000000000007;
expected.coordinate=367095935924581028343096807538245979939;
expected.virtual_floor=787551268719683502651961776892255047;
expected.virtual_ceil=787551268719683502651961776892255048;
expected.virtual_lower=787551268719683502651961776892255034;
expected.virtual_error_bound=14;
expected.principal_lower=366308384655861344840444845761353724892;
expected.principal_upper=366308384655861344840444845761353724905;
expected.paper_principal_floor=366308384655861344840444845761353724890;
expected.coordinate_error_bound=2;
expected.principal_error_bound=16;
expected.radial_slack_ceil=4;
expected.stored_slack_bound=9;
return (c, expected);
}
if(index==7){ // eight-ticks-8
c.tokens=new address[](8); c.decimals=new uint8[](8); c.initialAmountsRaw=new uint256[](8);
c.tickKeys=new uint64[](8); c.radiiInternal=new uint192[](8);
c.tokens[0]=address(1); c.decimals[0]=6; c.initialAmountsRaw[0]=23248107;
c.tokens[1]=address(2); c.decimals[1]=18; c.initialAmountsRaw[1]=23248106176783787642;
c.tokens[2]=address(3); c.decimals[2]=0; c.initialAmountsRaw[2]=24;
c.tokens[3]=address(4); c.decimals[3]=8; c.initialAmountsRaw[3]=2324810618;
c.tokens[4]=address(5); c.decimals[4]=6; c.initialAmountsRaw[4]=23248107;
c.tokens[5]=address(6); c.decimals[5]=18; c.initialAmountsRaw[5]=23248106176783787642;
c.tokens[6]=address(7); c.decimals[6]=0; c.initialAmountsRaw[6]=24;
c.tokens[7]=address(8); c.decimals[7]=8; c.initialAmountsRaw[7]=2324810618;
c.tickKeys[0]=29125246976; c.radiiInternal[0]=18446744073709551616000000000000000000;
c.tickKeys[1]=29259464704; c.radiiInternal[1]=36893488147419103232000000000000000001;
c.tickKeys[2]=29393682432; c.radiiInternal[2]=55340232221128654848000000000000000002;
c.tickKeys[3]=29527900160; c.radiiInternal[3]=73786976294838206464000000000000000003;
c.tickKeys[4]=29662117888; c.radiiInternal[4]=92233720368547758080000000000000000004;
c.tickKeys[5]=29796335616; c.radiiInternal[5]=110680464442257309696000000000000000005;
c.tickKeys[6]=29930553344; c.radiiInternal[6]=129127208515966861312000000000000000006;
c.tickKeys[7]=18446744073709551615; c.radiiInternal[7]=147573952589676412928000000000000000007;
expected.coordinate=429294065797553778353707707487454849380;
expected.virtual_floor=442200955997022160069008512894244104;
expected.virtual_ceil=442200955997022160069008512894244105;
expected.virtual_lower=442200955997022160069008512894244091;
expected.virtual_error_bound=14;
expected.principal_lower=428851864841556756193638698974560605276;
expected.principal_upper=428851864841556756193638698974560605289;
expected.paper_principal_floor=428851864841556756193638698974560605273;
expected.coordinate_error_bound=2;
expected.principal_error_bound=16;
expected.radial_slack_ceil=6;
expected.stored_slack_bound=9;
return (c, expected);
}
if(index==8){ // near-limit-2
c.tokens=new address[](2); c.decimals=new uint8[](2); c.initialAmountsRaw=new uint256[](2);
c.tickKeys=new uint64[](3); c.radiiInternal=new uint192[](3);
c.tokens[0]=address(1); c.decimals[0]=6; c.initialAmountsRaw[0]=19697082452475361;
c.tokens[1]=address(2); c.decimals[1]=18; c.initialAmountsRaw[1]=19697082452475360605687709476;
c.tickKeys[0]=3221225472; c.radiiInternal[0]=1461501637257115923462102552542731403655932542955;
c.tickKeys[1]=3758096384; c.radiiInternal[1]=18446744073709551616000000000003;
c.tickKeys[2]=18446744073709551615; c.radiiInternal[2]=73786976294838206464000000000000000017;
expected.coordinate=428063918858979211537310348709378508404329283584;
expected.virtual_floor=64716879859410952421163768539862642598464824851;
expected.virtual_ceil=64716879859410952421163768539862642598464824852;
expected.virtual_lower=64716879859410952421163768539862642581284955666;
expected.virtual_error_bound=17179869186;
expected.principal_lower=363347038999568259116146580169515865805864458733;
expected.principal_upper=363347038999568259116146580169515865823044327918;
expected.paper_principal_floor=363347038999568259116146580169515865805370620209;
expected.coordinate_error_bound=493838523;
expected.principal_error_bound=17673707709;
expected.radial_slack_ceil=698393137;
expected.stored_slack_bound=8589934594;
return (c, expected);
}
if(index==9){ // near-limit-3
c.tokens=new address[](3); c.decimals=new uint8[](3); c.initialAmountsRaw=new uint256[](3);
c.tickKeys=new uint64[](3); c.radiiInternal=new uint192[](3);
c.tokens[0]=address(1); c.decimals[0]=6; c.initialAmountsRaw[0]=32048628603374136;
c.tokens[1]=address(2); c.decimals[1]=18; c.initialAmountsRaw[1]=32048628603374135360064316382;
c.tokens[2]=address(3); c.decimals[2]=8; c.initialAmountsRaw[2]=3204862860337413537;
c.tickKeys[0]=7516192768; c.radiiInternal[0]=1461501637257115923462102552542731403655932542955;
c.tickKeys[1]=8053063680; c.radiiInternal[1]=18446744073709551616000000000003;
c.tickKeys[2]=18446744073709551615; c.radiiInternal[2]=73786976294838206464000000000000000017;
expected.coordinate=617703273596827311055657234733470453157351915520;
expected.virtual_floor=26510423837017055584783144833004673776138027570;
expected.virtual_ceil=26510423837017055584783144833004673776138027571;
expected.virtual_lower=26510423837017055584783144833004673758958158385;
expected.virtual_error_bound=17179869186;
expected.principal_lower=591192849759810255470874089900465779381213887950;
expected.principal_upper=591192849759810255470874089900465779398393757135;
expected.paper_principal_floor=591192849759810255470874089900465779381002245853;
expected.coordinate_error_bound=211642096;
expected.principal_error_bound=17391511282;
expected.radial_slack_ceil=366574862;
expected.stored_slack_bound=8589934594;
return (c, expected);
}
if(index==10){ // near-limit-5
c.tokens=new address[](5); c.decimals=new uint8[](5); c.initialAmountsRaw=new uint256[](5);
c.tickKeys=new uint64[](3); c.radiiInternal=new uint192[](3);
c.tokens[0]=address(1); c.decimals[0]=6; c.initialAmountsRaw[0]=43132307103106113;
c.tokens[1]=address(2); c.decimals[1]=18; c.initialAmountsRaw[1]=43132307103106112553328591759;
c.tokens[2]=address(3); c.decimals[2]=8; c.initialAmountsRaw[2]=4313230710310611256;
c.tokens[3]=address(4); c.decimals[3]=0; c.initialAmountsRaw[3]=43132307104;
c.tokens[4]=address(5); c.decimals[4]=6; c.initialAmountsRaw[4]=43132307103106113;
c.tickKeys[0]=16106127360; c.radiiInternal[0]=1461501637257115923462102552542731403655932542955;
c.tickKeys[1]=16642998272; c.radiiInternal[1]=18446744073709551616000000000003;
c.tickKeys[2]=18446744073709551615; c.radiiInternal[2]=73786976294838206464000000000000000017;
expected.coordinate=807898235271074272700838387609189502142656806912;
expected.virtual_floor=12247604831431192860836070384037072894165063759;
expected.virtual_ceil=12247604831431192860836070384037072894165063760;
expected.virtual_lower=12247604831431192860836070384037072876985194574;
expected.virtual_error_bound=17179869186;
expected.principal_lower=795650630439643079840002317225152429248491743153;
expected.principal_upper=795650630439643079840002317225152429265671612338;
expected.paper_principal_floor=795650630439643079840002317225152429246662970142;
expected.coordinate_error_bound=1828773011;
expected.principal_error_bound=19008642197;
expected.radial_slack_ceil=4089260767;
expected.stored_slack_bound=12884901891;
return (c, expected);
}
if(index==11){ // near-limit-8
c.tokens=new address[](8); c.decimals=new uint8[](8); c.initialAmountsRaw=new uint256[](8);
c.tickKeys=new uint64[](3); c.radiiInternal=new uint192[](3);
c.tokens[0]=address(1); c.decimals[0]=6; c.initialAmountsRaw[0]=50848968116584989;
c.tokens[1]=address(2); c.decimals[1]=18; c.initialAmountsRaw[1]=50848968116584988735615359304;
c.tokens[2]=address(3); c.decimals[2]=8; c.initialAmountsRaw[2]=5084896811658498874;
c.tokens[3]=address(4); c.decimals[3]=0; c.initialAmountsRaw[3]=50848968117;
c.tokens[4]=address(5); c.decimals[4]=6; c.initialAmountsRaw[4]=50848968116584989;
c.tokens[5]=address(6); c.decimals[5]=18; c.initialAmountsRaw[5]=50848968116584988735615359304;
c.tokens[6]=address(7); c.decimals[6]=8; c.initialAmountsRaw[6]=5084896811658498874;
c.tokens[7]=address(8); c.decimals[7]=0; c.initialAmountsRaw[7]=50848968117;
c.tickKeys[0]=28991029248; c.radiiInternal[0]=1461501637257115923462102552542731403655932542955;
c.tickKeys[1]=29527900160; c.radiiInternal[1]=18446744073709551616000000000003;
c.tickKeys[2]=18446744073709551615; c.radiiInternal[2]=73786976294838206464000000000000000017;
expected.coordinate=944782778094941064870497590712830764032278396928;
expected.virtual_floor=6784876836080983411957842322762650170364482759;
expected.virtual_ceil=6784876836080983411957842322762650170364482760;
expected.virtual_lower=6784876836080983411957842322762650153184613574;
expected.virtual_error_bound=17179869186;
expected.principal_lower=937997901258860081458539748390068113861913914169;
expected.principal_upper=937997901258860081458539748390068113879093783354;
expected.paper_principal_floor=937997901258860081458539748390068113859519511258;
expected.coordinate_error_bound=2394402910;
expected.principal_error_bound=19574272096;
expected.radial_slack_ceil=6772394138;
expected.stored_slack_bound=12884901891;
return (c, expected);
}
revert("Unknown oracle fixture");
}
}
