// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;
// Generated by packages/reference/fixtures_lower_sheet.py; exact pair-difference/bisection oracle.
library LowerSheetFixtures {
    struct Case { uint256[] point; uint8 output; uint256 sigma; uint256 lower; bool found; uint256 ceiling; }
    uint256 internal constant COUNT = 47;
    function get(uint256 index) internal pure returns (Case memory c) {
        if (index == 0) { // n2-small
            c.point = new uint256[](2);
            c.point[0] = 12;
            c.point[1] = 14;
            c.output = 1; c.sigma = 3; c.lower = 0;
            c.found = true; c.ceiling = 7; return c;
        }
        if (index == 1) { // n2-varied-64
            c.point = new uint256[](2);
            c.point[0] = 18446744073709551616;
            c.point[1] = 19023204826012975104;
            c.output = 1; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 9750865523487696808; return c;
        }
        if (index == 2) { // n2-varied-191
            c.point = new uint256[](2);
            c.point[0] = 3138550867693340381917894711603833208051177722232017256448;
            c.point[1] = 3236630582308757268852828921341452995802777026051767795712;
            c.output = 1; c.sigma = 1046183622564446793972631570534611069350392574077339085482; c.lower = 0;
            c.found = true; c.ceiling = 1659023799930084577138169514370989903376970706578869853500; return c;
        }
        if (index == 3) { // n2-already-below
            c.point = new uint256[](2);
            c.point[0] = 18446744073709551616;
            c.point[1] = 0;
            c.output = 1; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 0; return c;
        }
        if (index == 4) { // n2-caller-lower
            c.point = new uint256[](2);
            c.point[0] = 18446744073709551616;
            c.point[1] = 19023204826012975104;
            c.output = 1; c.sigma = 6148914691236517205; c.lower = 19023204826012975104;
            c.found = false; c.ceiling = 9750865523487696808; return c;
        }
        if (index == 5) { // n2-spread
            c.point = new uint256[](2);
            c.point[0] = 0;
            c.point[1] = 10;
            c.output = 1; c.sigma = 1; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 6) { // n3-small
            c.point = new uint256[](3);
            c.point[0] = 13;
            c.point[1] = 10;
            c.point[2] = 12;
            c.output = 1; c.sigma = 3; c.lower = 0;
            c.found = true; c.ceiling = 8; return c;
        }
        if (index == 7) { // n3-varied-64
            c.point = new uint256[](3);
            c.point[0] = 18734974449861263360;
            c.point[1] = 17870283321406128128;
            c.point[2] = 18446744073709551616;
            c.output = 1; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 11064145486315133061; return c;
        }
        if (index == 8) { // n3-varied-191
            c.point = new uint256[](3);
            c.point[0] = 3187590725001048825385361816472643101926977374141892526080;
            c.point[1] = 3040471153077923494982960501866213420299578418412266717184;
            c.point[2] = 3138550867693340381917894711603833208051177722232017256448;
            c.output = 1; c.sigma = 1046183622564446793972631570534611069350392574077339085482; c.lower = 0;
            c.found = true; c.ceiling = 1882466807020465621595546396708688721500756874325082075635; return c;
        }
        if (index == 9) { // n3-already-below
            c.point = new uint256[](3);
            c.point[0] = 18734974449861263360;
            c.point[1] = 0;
            c.point[2] = 18446744073709551616;
            c.output = 1; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 0; return c;
        }
        if (index == 10) { // n3-caller-lower
            c.point = new uint256[](3);
            c.point[0] = 18734974449861263360;
            c.point[1] = 17870283321406128128;
            c.point[2] = 18446744073709551616;
            c.output = 1; c.sigma = 6148914691236517205; c.lower = 17870283321406128128;
            c.found = false; c.ceiling = 11064145486315133061; return c;
        }
        if (index == 11) { // n3-spread
            c.point = new uint256[](3);
            c.point[0] = 0;
            c.point[1] = 10;
            c.point[2] = 0;
            c.output = 1; c.sigma = 1; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 12) { // n4-small
            c.point = new uint256[](4);
            c.point[0] = 14;
            c.point[1] = 11;
            c.point[2] = 13;
            c.point[3] = 10;
            c.output = 2; c.sigma = 3; c.lower = 0;
            c.found = true; c.ceiling = 11; return c;
        }
        if (index == 13) { // n4-varied-64
            c.point = new uint256[](4);
            c.point[0] = 19023204826012975104;
            c.point[1] = 18158513697557839872;
            c.point[2] = 18734974449861263360;
            c.point[3] = 17870283321406128128;
            c.output = 2; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 11318441139828079582; return c;
        }
        if (index == 14) { // n4-varied-191
            c.point = new uint256[](4);
            c.point[0] = 3236630582308757268852828921341452995802777026051767795712;
            c.point[1] = 3089511010385631938450427606735023314175378070322141986816;
            c.point[2] = 3187590725001048825385361816472643101926977374141892526080;
            c.point[3] = 3040471153077923494982960501866213420299578418412266717184;
            c.output = 2; c.sigma = 1046183622564446793972631570534611069350392574077339085482; c.lower = 0;
            c.found = true; c.ceiling = 1925732970458011772729606046274665534438812682768600862087; return c;
        }
        if (index == 15) { // n4-already-below
            c.point = new uint256[](4);
            c.point[0] = 19023204826012975104;
            c.point[1] = 18158513697557839872;
            c.point[2] = 0;
            c.point[3] = 17870283321406128128;
            c.output = 2; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 0; return c;
        }
        if (index == 16) { // n4-caller-lower
            c.point = new uint256[](4);
            c.point[0] = 19023204826012975104;
            c.point[1] = 18158513697557839872;
            c.point[2] = 18734974449861263360;
            c.point[3] = 17870283321406128128;
            c.output = 2; c.sigma = 6148914691236517205; c.lower = 18734974449861263360;
            c.found = false; c.ceiling = 11318441139828079582; return c;
        }
        if (index == 17) { // n4-spread
            c.point = new uint256[](4);
            c.point[0] = 0;
            c.point[1] = 10;
            c.point[2] = 0;
            c.point[3] = 10;
            c.output = 2; c.sigma = 1; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 18) { // n5-small
            c.point = new uint256[](5);
            c.point[0] = 10;
            c.point[1] = 12;
            c.point[2] = 14;
            c.point[3] = 11;
            c.point[4] = 13;
            c.output = 2; c.sigma = 3; c.lower = 0;
            c.found = true; c.ceiling = 9; return c;
        }
        if (index == 19) { // n5-varied-64
            c.point = new uint256[](5);
            c.point[0] = 17870283321406128128;
            c.point[1] = 18446744073709551616;
            c.point[2] = 19023204826012975104;
            c.point[3] = 18158513697557839872;
            c.point[4] = 18734974449861263360;
            c.output = 2; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 11465801392982088743; return c;
        }
        if (index == 20) { // n5-varied-191
            c.point = new uint256[](5);
            c.point[0] = 3040471153077923494982960501866213420299578418412266717184;
            c.point[1] = 3138550867693340381917894711603833208051177722232017256448;
            c.point[2] = 3236630582308757268852828921341452995802777026051767795712;
            c.point[3] = 3089511010385631938450427606735023314175378070322141986816;
            c.point[4] = 3187590725001048825385361816472643101926977374141892526080;
            c.output = 2; c.sigma = 1046183622564446793972631570534611069350392574077339085482; c.lower = 0;
            c.found = true; c.ceiling = 1950805018324669235115025414592247794358894761336784029978; return c;
        }
        if (index == 21) { // n5-already-below
            c.point = new uint256[](5);
            c.point[0] = 17870283321406128128;
            c.point[1] = 18446744073709551616;
            c.point[2] = 0;
            c.point[3] = 18158513697557839872;
            c.point[4] = 18734974449861263360;
            c.output = 2; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 0; return c;
        }
        if (index == 22) { // n5-caller-lower
            c.point = new uint256[](5);
            c.point[0] = 17870283321406128128;
            c.point[1] = 18446744073709551616;
            c.point[2] = 19023204826012975104;
            c.point[3] = 18158513697557839872;
            c.point[4] = 18734974449861263360;
            c.output = 2; c.sigma = 6148914691236517205; c.lower = 19023204826012975104;
            c.found = false; c.ceiling = 11465801392982088743; return c;
        }
        if (index == 23) { // n5-spread
            c.point = new uint256[](5);
            c.point[0] = 0;
            c.point[1] = 10;
            c.point[2] = 0;
            c.point[3] = 10;
            c.point[4] = 0;
            c.output = 2; c.sigma = 1; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 24) { // n6-small
            c.point = new uint256[](6);
            c.point[0] = 11;
            c.point[1] = 13;
            c.point[2] = 10;
            c.point[3] = 12;
            c.point[4] = 14;
            c.point[5] = 11;
            c.output = 3; c.sigma = 3; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 25) { // n6-varied-64
            c.point = new uint256[](6);
            c.point[0] = 18158513697557839872;
            c.point[1] = 18734974449861263360;
            c.point[2] = 17870283321406128128;
            c.point[3] = 18446744073709551616;
            c.point[4] = 19023204826012975104;
            c.point[5] = 18158513697557839872;
            c.output = 3; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 11733701122293736689; return c;
        }
        if (index == 26) { // n6-varied-191
            c.point = new uint256[](6);
            c.point[0] = 3089511010385631938450427606735023314175378070322141986816;
            c.point[1] = 3187590725001048825385361816472643101926977374141892526080;
            c.point[2] = 3040471153077923494982960501866213420299578418412266717184;
            c.point[3] = 3138550867693340381917894711603833208051177722232017256448;
            c.point[4] = 3236630582308757268852828921341452995802777026051767795712;
            c.point[5] = 3089511010385631938450427606735023314175378070322141986816;
            c.output = 3; c.sigma = 1046183622564446793972631570534611069350392574077339085482; c.lower = 0;
            c.found = true; c.ceiling = 1996385795318492374990284821026144427161286906934553993069; return c;
        }
        if (index == 27) { // n6-already-below
            c.point = new uint256[](6);
            c.point[0] = 18158513697557839872;
            c.point[1] = 18734974449861263360;
            c.point[2] = 17870283321406128128;
            c.point[3] = 0;
            c.point[4] = 19023204826012975104;
            c.point[5] = 18158513697557839872;
            c.output = 3; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 0; return c;
        }
        if (index == 28) { // n6-caller-lower
            c.point = new uint256[](6);
            c.point[0] = 18158513697557839872;
            c.point[1] = 18734974449861263360;
            c.point[2] = 17870283321406128128;
            c.point[3] = 18446744073709551616;
            c.point[4] = 19023204826012975104;
            c.point[5] = 18158513697557839872;
            c.output = 3; c.sigma = 6148914691236517205; c.lower = 18446744073709551616;
            c.found = false; c.ceiling = 11733701122293736689; return c;
        }
        if (index == 29) { // n6-spread
            c.point = new uint256[](6);
            c.point[0] = 0;
            c.point[1] = 10;
            c.point[2] = 0;
            c.point[3] = 10;
            c.point[4] = 0;
            c.point[5] = 10;
            c.output = 3; c.sigma = 1; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 30) { // n7-small
            c.point = new uint256[](7);
            c.point[0] = 12;
            c.point[1] = 14;
            c.point[2] = 11;
            c.point[3] = 13;
            c.point[4] = 10;
            c.point[5] = 12;
            c.point[6] = 14;
            c.output = 3; c.sigma = 3; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 31) { // n7-varied-64
            c.point = new uint256[](7);
            c.point[0] = 18446744073709551616;
            c.point[1] = 19023204826012975104;
            c.point[2] = 18158513697557839872;
            c.point[3] = 18734974449861263360;
            c.point[4] = 17870283321406128128;
            c.point[5] = 18446744073709551616;
            c.point[6] = 19023204826012975104;
            c.output = 3; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 11947505659113545517; return c;
        }
        if (index == 32) { // n7-varied-191
            c.point = new uint256[](7);
            c.point[0] = 3138550867693340381917894711603833208051177722232017256448;
            c.point[1] = 3236630582308757268852828921341452995802777026051767795712;
            c.point[2] = 3089511010385631938450427606735023314175378070322141986816;
            c.point[3] = 3187590725001048825385361816472643101926977374141892526080;
            c.point[4] = 3040471153077923494982960501866213420299578418412266717184;
            c.point[5] = 3138550867693340381917894711603833208051177722232017256448;
            c.point[6] = 3236630582308757268852828921341452995802777026051767795712;
            c.output = 3; c.sigma = 1046183622564446793972631570534611069350392574077339085482; c.lower = 0;
            c.found = true; c.ceiling = 2032762752242232117506415937147513657442162726684129391950; return c;
        }
        if (index == 33) { // n7-already-below
            c.point = new uint256[](7);
            c.point[0] = 18446744073709551616;
            c.point[1] = 19023204826012975104;
            c.point[2] = 18158513697557839872;
            c.point[3] = 0;
            c.point[4] = 17870283321406128128;
            c.point[5] = 18446744073709551616;
            c.point[6] = 19023204826012975104;
            c.output = 3; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 0; return c;
        }
        if (index == 34) { // n7-caller-lower
            c.point = new uint256[](7);
            c.point[0] = 18446744073709551616;
            c.point[1] = 19023204826012975104;
            c.point[2] = 18158513697557839872;
            c.point[3] = 18734974449861263360;
            c.point[4] = 17870283321406128128;
            c.point[5] = 18446744073709551616;
            c.point[6] = 19023204826012975104;
            c.output = 3; c.sigma = 6148914691236517205; c.lower = 18734974449861263360;
            c.found = false; c.ceiling = 11947505659113545517; return c;
        }
        if (index == 35) { // n7-spread
            c.point = new uint256[](7);
            c.point[0] = 0;
            c.point[1] = 10;
            c.point[2] = 0;
            c.point[3] = 10;
            c.point[4] = 0;
            c.point[5] = 10;
            c.point[6] = 0;
            c.output = 3; c.sigma = 1; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 36) { // n8-small
            c.point = new uint256[](8);
            c.point[0] = 13;
            c.point[1] = 10;
            c.point[2] = 12;
            c.point[3] = 14;
            c.point[4] = 11;
            c.point[5] = 13;
            c.point[6] = 10;
            c.point[7] = 12;
            c.output = 4; c.sigma = 3; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 37) { // n8-varied-64
            c.point = new uint256[](8);
            c.point[0] = 18734974449861263360;
            c.point[1] = 17870283321406128128;
            c.point[2] = 18446744073709551616;
            c.point[3] = 19023204826012975104;
            c.point[4] = 18158513697557839872;
            c.point[5] = 18734974449861263360;
            c.point[6] = 17870283321406128128;
            c.point[7] = 18446744073709551616;
            c.output = 4; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 11975173066932076295; return c;
        }
        if (index == 38) { // n8-varied-191
            c.point = new uint256[](8);
            c.point[0] = 3187590725001048825385361816472643101926977374141892526080;
            c.point[1] = 3040471153077923494982960501866213420299578418412266717184;
            c.point[2] = 3138550867693340381917894711603833208051177722232017256448;
            c.point[3] = 3236630582308757268852828921341452995802777026051767795712;
            c.point[4] = 3089511010385631938450427606735023314175378070322141986816;
            c.point[5] = 3187590725001048825385361816472643101926977374141892526080;
            c.point[6] = 3040471153077923494982960501866213420299578418412266717184;
            c.point[7] = 3138550867693340381917894711603833208051177722232017256448;
            c.output = 4; c.sigma = 1046183622564446793972631570534611069350392574077339085482; c.lower = 0;
            c.found = true; c.ceiling = 2037470117751760383565112042374323689754319044389359251332; return c;
        }
        if (index == 39) { // n8-already-below
            c.point = new uint256[](8);
            c.point[0] = 18734974449861263360;
            c.point[1] = 17870283321406128128;
            c.point[2] = 18446744073709551616;
            c.point[3] = 19023204826012975104;
            c.point[4] = 0;
            c.point[5] = 18734974449861263360;
            c.point[6] = 17870283321406128128;
            c.point[7] = 18446744073709551616;
            c.output = 4; c.sigma = 6148914691236517205; c.lower = 0;
            c.found = true; c.ceiling = 0; return c;
        }
        if (index == 40) { // n8-caller-lower
            c.point = new uint256[](8);
            c.point[0] = 18734974449861263360;
            c.point[1] = 17870283321406128128;
            c.point[2] = 18446744073709551616;
            c.point[3] = 19023204826012975104;
            c.point[4] = 18158513697557839872;
            c.point[5] = 18734974449861263360;
            c.point[6] = 17870283321406128128;
            c.point[7] = 18446744073709551616;
            c.output = 4; c.sigma = 6148914691236517205; c.lower = 18158513697557839872;
            c.found = false; c.ceiling = 11975173066932076295; return c;
        }
        if (index == 41) { // n8-spread
            c.point = new uint256[](8);
            c.point[0] = 0;
            c.point[1] = 10;
            c.point[2] = 0;
            c.point[3] = 10;
            c.point[4] = 0;
            c.point[5] = 10;
            c.point[6] = 0;
            c.point[7] = 10;
            c.output = 4; c.sigma = 1; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 42) { // exact-sheet-edge
            c.point = new uint256[](4);
            c.point[0] = 1;
            c.point[1] = 0;
            c.point[2] = 2;
            c.point[3] = 2;
            c.output = 0; c.sigma = 2; c.lower = 0;
            c.found = true; c.ceiling = 0; return c;
        }
        if (index == 43) { // zero-sigma
            c.point = new uint256[](3);
            c.point[0] = 10;
            c.point[1] = 11;
            c.point[2] = 12;
            c.output = 0; c.sigma = 0; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 44) { // no-nonnegative-side
            c.point = new uint256[](3);
            c.point[0] = 10;
            c.point[1] = 0;
            c.point[2] = 0;
            c.output = 0; c.sigma = 3; c.lower = 0;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 45) { // lower-above-current
            c.point = new uint256[](3);
            c.point[0] = 10;
            c.point[1] = 11;
            c.point[2] = 12;
            c.output = 0; c.sigma = 3; c.lower = 11;
            c.found = false; c.ceiling = 0; return c;
        }
        if (index == 46) { // exact-caller-lower
            c.point = new uint256[](3);
            c.point[0] = 10;
            c.point[1] = 11;
            c.point[2] = 12;
            c.output = 0; c.sigma = 3; c.lower = 7;
            c.found = true; c.ceiling = 7; return c;
        }
        revert("fixture index");
    }
}
