// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;
// Generated by scripts/generate-pilot-gas-fixtures.py; do not hand-edit.
import {OrbitalMath as M} from "../../src/libraries/OrbitalMath.sol";
import {TickGeometry as G} from "../../src/libraries/TickGeometry.sol";
library PilotGasFixtures {
    struct Case {uint256[] x;M.Tick[] ticks;uint8[] decimals;uint8 input;uint8 output;uint256 raw;
        uint256 expectedOut;uint256[] expectedReserves;uint8 originalPrefix;uint8 initialPrefix;uint8 finalPrefix;
        uint64[] transitionKeys;bool[] transitionInward;}
    function get(uint8 step) internal pure returns(Case memory c) {
        require(step>=1&&step<=3,"fixture step");
        c.x=new uint256[](8);c.ticks=new M.Tick[](8);c.decimals=new uint8[](8);c.expectedReserves=new uint256[](8);
        if(step==1) { // n8-t8-concentrated-step1
            c.input=0;c.output=7;c.raw=487210071140765;c.expectedOut=424487457;
            c.originalPrefix=0;c.initialPrefix=0;c.finalPrefix=7;
            c.x[0]=133064305051838779553083268398644462742790281255;c.expectedReserves[0]=142051744544306295358828518167870702742790281255;c.decimals[0]=6;
            c.ticks[0]=M.Tick(22212260658,18446744073709551616000000000000000000000,G.coefficients(8,22212260658));
            c.x[1]=132498167131053432215484544429128942742790281255;c.expectedReserves[1]=132498167131053432215484544429128942742790281255;c.decimals[1]=8;
            c.ticks[1]=M.Tick(22212784946,184467440737095516160000000000000000000000,G.coefficients(8,22212784946));
            c.x[2]=132498167131053432215484544429128942742790281255;c.expectedReserves[2]=132498167131053432215484544429128942742790281255;c.decimals[2]=18;
            c.ticks[2]=M.Tick(22213309234,1844674407370955161600000000000000000000000,G.coefficients(8,22213309234));
            c.x[3]=132498167131053432215484544429128942742790281255;c.expectedReserves[3]=132498167131053432215484544429128942742790281255;c.decimals[3]=0;
            c.ticks[3]=M.Tick(22213833522,18446744073709551616000000000000000000000000,G.coefficients(8,22213833522));
            c.x[4]=132498167131053432215484544429128942742790281255;c.expectedReserves[4]=132498167131053432215484544429128942742790281255;c.decimals[4]=6;
            c.ticks[4]=M.Tick(22214357810,184467440737095516160000000000000000000000000,G.coefficients(8,22214357810));
            c.x[5]=132498167131053432215484544429128942742790281255;c.expectedReserves[5]=132498167131053432215484544429128942742790281255;c.decimals[5]=8;
            c.ticks[5]=M.Tick(22214882098,1844674407370955161600000000000000000000000000,G.coefficients(8,22214882098));
            c.x[6]=132498167131053432215484544429128942742790281255;c.expectedReserves[6]=132498167131053432215484544429128942742790281255;c.decimals[6]=18;
            c.ticks[6]=M.Tick(22215406386,18446744073709551616000000000000000000000000000,G.coefficients(8,22215406386));
            c.x[7]=131936418026083673569089336749128942742790281255;c.expectedReserves[7]=124106006544304885447003256237128942742790281255;c.decimals[7]=0;
            c.ticks[7]=M.Tick(type(uint64).max,184467440737095516160000000000000000000000000000,G.coefficients(8,type(uint64).max));
            c.transitionKeys=new uint64[](7);c.transitionInward=new bool[](7);
            c.transitionKeys[0]=22212260658;c.transitionInward[0]=false;
            c.transitionKeys[1]=22212784946;c.transitionInward[1]=false;
            c.transitionKeys[2]=22213309234;c.transitionInward[2]=false;
            c.transitionKeys[3]=22213833522;c.transitionInward[3]=false;
            c.transitionKeys[4]=22214357810;c.transitionInward[4]=false;
            c.transitionKeys[5]=22214882098;c.transitionInward[5]=false;
            c.transitionKeys[6]=22215406386;c.transitionInward[6]=false;
        }
        if(step==2) { // n8-t8-concentrated-step2
            c.input=7;c.output=0;c.raw=1643741589;c.expectedOut=1405683905086740;
            c.originalPrefix=7;c.initialPrefix=7;c.finalPrefix=7;
            c.x[0]=142051744544306295358828518167870702742790281255;c.expectedReserves[0]=116121453298638574426497011180698862742790281255;c.decimals[0]=6;
            c.ticks[0]=M.Tick(22212260658,18446744073709551616000000000000000000000,G.coefficients(8,22212260658));
            c.x[1]=132498167131053432215484544429128942742790281255;c.expectedReserves[1]=132498167131053432215484544429128942742790281255;c.decimals[1]=8;
            c.ticks[1]=M.Tick(22212784946,184467440737095516160000000000000000000000,G.coefficients(8,22212784946));
            c.x[2]=132498167131053432215484544429128942742790281255;c.expectedReserves[2]=132498167131053432215484544429128942742790281255;c.decimals[2]=18;
            c.ticks[2]=M.Tick(22213309234,1844674407370955161600000000000000000000000,G.coefficients(8,22213309234));
            c.x[3]=132498167131053432215484544429128942742790281255;c.expectedReserves[3]=132498167131053432215484544429128942742790281255;c.decimals[3]=0;
            c.ticks[3]=M.Tick(22213833522,18446744073709551616000000000000000000000000,G.coefficients(8,22213833522));
            c.x[4]=132498167131053432215484544429128942742790281255;c.expectedReserves[4]=132498167131053432215484544429128942742790281255;c.decimals[4]=6;
            c.ticks[4]=M.Tick(22214357810,184467440737095516160000000000000000000000000,G.coefficients(8,22214357810));
            c.x[5]=132498167131053432215484544429128942742790281255;c.expectedReserves[5]=132498167131053432215484544429128942742790281255;c.decimals[5]=8;
            c.ticks[5]=M.Tick(22214882098,1844674407370955161600000000000000000000000000,G.coefficients(8,22214882098));
            c.x[6]=132498167131053432215484544429128942742790281255;c.expectedReserves[6]=132498167131053432215484544429128942742790281255;c.decimals[6]=18;
            c.ticks[6]=M.Tick(22215406386,18446744073709551616000000000000000000000000000,G.coefficients(8,22215406386));
            c.x[7]=124106006544304885447003256237128942742790281255;c.expectedReserves[7]=154427686959900556944764614061128942742790281255;c.decimals[7]=0;
            c.ticks[7]=M.Tick(type(uint64).max,184467440737095516160000000000000000000000000000,G.coefficients(8,type(uint64).max));
            c.transitionKeys=new uint64[](14);c.transitionInward=new bool[](14);
            c.transitionKeys[0]=22215406386;c.transitionInward[0]=true;
            c.transitionKeys[1]=22214882098;c.transitionInward[1]=true;
            c.transitionKeys[2]=22214357810;c.transitionInward[2]=true;
            c.transitionKeys[3]=22213833522;c.transitionInward[3]=true;
            c.transitionKeys[4]=22213309234;c.transitionInward[4]=true;
            c.transitionKeys[5]=22212784946;c.transitionInward[5]=true;
            c.transitionKeys[6]=22212260658;c.transitionInward[6]=true;
            c.transitionKeys[7]=22212260658;c.transitionInward[7]=false;
            c.transitionKeys[8]=22212784946;c.transitionInward[8]=false;
            c.transitionKeys[9]=22213309234;c.transitionInward[9]=false;
            c.transitionKeys[10]=22213833522;c.transitionInward[10]=false;
            c.transitionKeys[11]=22214357810;c.transitionInward[11]=false;
            c.transitionKeys[12]=22214882098;c.transitionInward[12]=false;
            c.transitionKeys[13]=22215406386;c.transitionInward[13]=false;
        }
        if(step==3) { // n8-t8-concentrated-step3
            c.input=1;c.output=0;c.raw=6138079636419094;c.expectedOut=48556339518337;
            c.originalPrefix=7;c.initialPrefix=7;c.finalPrefix=7;
            c.x[0]=116121453298638574426497011180698862742790281255;c.expectedReserves[0]=115225746930387662467758129500716270742790281255;c.decimals[0]=6;
            c.ticks[0]=M.Tick(22212260658,18446744073709551616000000000000000000000,G.coefficients(8,22212260658));
            c.x[1]=132498167131053432215484544429128942742790281255;c.expectedReserves[1]=133630442972624144230621421655138501782790281255;c.decimals[1]=8;
            c.ticks[1]=M.Tick(22212784946,184467440737095516160000000000000000000000,G.coefficients(8,22212784946));
            c.x[2]=132498167131053432215484544429128942742790281255;c.expectedReserves[2]=132498167131053432215484544429128942742790281255;c.decimals[2]=18;
            c.ticks[2]=M.Tick(22213309234,1844674407370955161600000000000000000000000,G.coefficients(8,22213309234));
            c.x[3]=132498167131053432215484544429128942742790281255;c.expectedReserves[3]=132498167131053432215484544429128942742790281255;c.decimals[3]=0;
            c.ticks[3]=M.Tick(22213833522,18446744073709551616000000000000000000000000,G.coefficients(8,22213833522));
            c.x[4]=132498167131053432215484544429128942742790281255;c.expectedReserves[4]=132498167131053432215484544429128942742790281255;c.decimals[4]=6;
            c.ticks[4]=M.Tick(22214357810,184467440737095516160000000000000000000000000,G.coefficients(8,22214357810));
            c.x[5]=132498167131053432215484544429128942742790281255;c.expectedReserves[5]=132498167131053432215484544429128942742790281255;c.decimals[5]=8;
            c.ticks[5]=M.Tick(22214882098,1844674407370955161600000000000000000000000000,G.coefficients(8,22214882098));
            c.x[6]=132498167131053432215484544429128942742790281255;c.expectedReserves[6]=132498167131053432215484544429128942742790281255;c.decimals[6]=18;
            c.ticks[6]=M.Tick(22215406386,18446744073709551616000000000000000000000000000,G.coefficients(8,22215406386));
            c.x[7]=154427686959900556944764614061128942742790281255;c.expectedReserves[7]=154427686959900556944764614061128942742790281255;c.decimals[7]=0;
            c.ticks[7]=M.Tick(type(uint64).max,184467440737095516160000000000000000000000000000,G.coefficients(8,type(uint64).max));
            c.transitionKeys=new uint64[](0);c.transitionInward=new bool[](0);
        }
    }
}
