'use client';
import Link from '../components/AppLink';
import {useState,useEffect} from 'react';
import {useStrategyPublication} from './useStrategyPublication';
import {StrategyAdminView} from './StrategyAdmin';
import type {StrategyProfileInput} from '@orbital/sdk';

import {presets} from '../content';
import styles from './Liquidity.module.css';
import {Select} from '../components/Select';
import TokenIcon from '../components/TokenIcon';
export {default as Liquidity} from './Strategies';
export function NewStrategy(){
 const [step,setStep]=useState(0),[allocation,setAllocation]=useState('10'),[preset,setPreset]=useState(1),[fee,setFee]=useState('500'),[risk,setRisk]=useState(false),[shared,setShared]=useState(false);
 const publication=useStrategyPublication(),choice=presets[preset]!;
 useEffect(()=>{if(publication.draft&&publication.profile){setStep(3);setAllocation(publication.profile.allocation);setPreset(presets.findIndex(p=>p.name===publication.profile!.preset));setFee(String(publication.profile.feePpm));}else if(!publication.draft){setStep(s=>s===3?2:s);}},[publication.draft,publication.profile]);
 return <section className={`page ${styles.page}`}><Link href="/liquidity" className="back-link"><span aria-hidden="true">←</span> Your liquidity</Link><div className={styles.header}><h1>Provide <em>liquidity.</em></h1><p>Choose your allocation and concentration.</p></div><ol className={styles.steps}>{['Assets','Concentration','Review','Publish'].map((name,i)=><li key={name} aria-current={step===i?'step':undefined}><span>{i+1}</span>{name}</li>)}</ol>
 <div className={styles.wizard}><div className={styles.form}>
 {step===0&&<><h2>Start with your assets.</h2><p className="hint"><Link className="inline-link" href="/fund">Get demo tokens <span aria-hidden="true">→</span></Link></p><p className="hint">Equal initial amounts of each asset. Your tokens stay in your wallet.</p><div className={styles.assets}>{['USDC','oUSD6','oUSD18'].map((s,i)=><div className="row" key={s}><TokenIcon symbol={s} size={36}/><div><strong>{s}</strong><div className="hint">{i===0?`${publication.network} settlement asset`:i===1?'6 decimal places':'18 decimal places'}</div></div></div>)}</div><div className="field"><label htmlFor="allocation">Allocate per asset</label><input id="allocation" type="text" inputMode="decimal" autoComplete="off" value={allocation} onChange={e=>setAllocation(e.target.value)}/><span className="hint">10–1,000,000 units per asset, subject to funding and numerical limits.</span></div><button className="button full" onClick={()=>setStep(1)} disabled={!/^\d+$/.test(allocation)||BigInt(allocation||'0')<10n||BigInt(allocation||'0')>1000000n}>Choose concentration</button></>}
 {step===1&&<><h2>Choose a profile.</h2><div className={styles.presets}>{presets.map((p,i)=><button key={p.name} className={styles.preset} aria-pressed={i===preset} onClick={()=>setPreset(i)}><strong>{p.name}</strong><span>{p.description}</span></button>)}</div><div className="field"><label htmlFor="fee">Swap fee</label><Select id="fee" value={fee} onValueChange={setFee} options={[{value:"100",label:"0.01%"},{value:"500",label:"0.05%"},{value:"1000",label:"0.10%"}]}/></div><button className="button full" onClick={()=>setStep(2)}>Review strategy</button></>}
 {step===2&&<><h2>Review your intent.</h2><p className="notice">This strategy includes oUSD6 and oUSD18 demo tokens with no redemption value.</p><div className="stack"><div className="row"><span>Per asset</span><strong>{allocation} units</strong></div><div className="row"><span>Concentration</span><strong>{choice.name}</strong></div><div className="row"><span>Fee</span><strong>{fee==='500'?'0.05%':fee==='100'?'0.01%':'0.10%'}</strong></div><p className="notice">Aqua approval targets are capped at four times your initial allocation. Review each transaction before signing.</p><label className={styles.check}><input type="checkbox" checked={shared} onChange={e=>setShared(e.target.checked)}/>I understand that other wallet activity can make this allocation unavailable.</label><label className={styles.check}><input type="checkbox" checked={risk} onChange={e=>setRisk(e.target.checked)}/>I understand that a depeg can change the tokens and value I hold.</label><button className="button full" disabled={!risk||!shared||publication.busy||(!publication.ready&&publication.connected&&!publication.wrongChain)} onClick={()=>{if(!publication.connected){publication.connect();return;}if(publication.wrongChain){void publication.switchNetwork?.();return;}publication.start({allocation,preset:choice.name as StrategyProfileInput["preset"],feePpm:Number(fee) as StrategyProfileInput["feePpm"]});}}>{!publication.connected?'Connect wallet':publication.wrongChain?'Switch network':publication.busy?'Preparing configuration…':'Prepare publication'}</button>{publication.error&&<p className="notice" role="alert">{publication.error}</p>}</div></>}
 {step===3&&<><h2>Publish from your wallet.</h2>{publication.restored&&<p className="notice">Saved publication restored. Completed onchain steps are checked before the next review.</p>}{publication.view&&<><p>{publication.network} · Maker nonce {publication.view.nonce}</p><dl className={styles.allocations}>{publication.view.allocations.map(t=><div key={t.symbol}><dt>{t.symbol}</dt><dd>{t.amount} allocated · {t.cap} Aqua approval target (if needed)</dd></div>)}</dl><details><summary>Quantized curve configuration</summary><p className="mono">{publication.view.hash}</p><ol>{publication.view.ticks.map(t=><li key={t.key}><p>{t.share}% · Realized reference threshold: {t.threshold}</p><p className="mono">Key: {t.key}<br/>Radius: {t.radius}</p></li>)}</ol></details></>}{publication.error&&<p className="notice">{publication.error}</p>}{publication.active&&!publication.admin.pending?<div className="stack"><p className="notice">Strategy is active. The index will show its receipt shortly.</p><Link className="button full" href={`/liquidity/${publication.view!.hash}`}>View strategy</Link><button className="button secondary" onClick={()=>{publication.newDraft();setStep(0);}}>Create another strategy</button></div>:<><>{publication.admin.review&&<p className="notice">This publication includes oUSD6 and oUSD18 demo tokens with no redemption value.</p>}<StrategyAdminView state={publication.admin} publication/></><button className="button secondary" disabled={publication.busy||publication.admin.busy||!!publication.admin.pending} onClick={publication.editDraft}>Edit unshipped configuration</button></>}</>}
 {step>0&&!publication.draft&&<button className={styles.backButton} onClick={()=>setStep(step-1)}>← Back</button>}</div><aside className={styles.preview}><h3>{choice.name}</h3><p className="hint">Initial funded principal allocation</p>{choice.shares.map((share,i)=><div className={styles.share} key={i}><span>{choice.thresholds[i]}</span><strong>{share}%</strong></div>)}<p className={`hint ${styles.previewNote}`}>Reference thresholds describe a single-coin depeg, not guaranteed price floors. Exact thresholds appear at publication.</p></aside></div></section>;
}
