'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {useStrategyPublication} from './useStrategyPublication';
import {StrategyAdminView} from './StrategyAdmin';
import type {StrategyProfileInput} from '@orbital/sdk';

import {presets} from '../content';
import styles from './Liquidity.module.css';
export {default as Liquidity} from './Strategies';
export function NewStrategy(){
 const [step,setStep]=useState(0),[allocation,setAllocation]=useState('10'),[preset,setPreset]=useState(1),[fee,setFee]=useState('500'),[risk,setRisk]=useState(false),[shared,setShared]=useState(false);
 const publication=useStrategyPublication(),choice=presets[preset]!;
 useEffect(()=>{if(publication.draft&&publication.profile){setStep(3);setAllocation(publication.profile.allocation);setPreset(presets.findIndex(p=>p.name===publication.profile!.preset));setFee(String(publication.profile.feePpm));}else if(!publication.draft){setStep(s=>s===3?2:s);}},[publication.draft,publication.profile]);
 return <section className="page"><Link href="/liquidity" className={styles.back}>← Your liquidity</Link><div className="page-head"><div><div className="eyebrow">Build a strategy</div><h1>Find your concentration.</h1><p>One wallet. Three assets. Your choice of exposure.</p></div></div><ol className={styles.steps}>{['Assets','Concentration','Review','Publish'].map((name,i)=><li key={name} aria-current={step===i?'step':undefined}><span>{i+1}</span>{name}</li>)}</ol>
 <div className={styles.wizard}><div className="panel">
 {step===0&&<><h2>Start with your assets.</h2><p className="hint"><Link href="/fund">Get demo tokens</Link></p><p className="hint">Equal initial amounts of each asset. Your tokens stay in your wallet.</p><div className={styles.assets}>{['USDC','oUSD6','oUSD18'].map((s,i)=><div className="row" key={s}><span className={styles.assetDot}>{i===0?'$':i===1?'6':'18'}</span><div><strong>{s}</strong><div className="hint">{i===0?`${publication.network} settlement asset`:'Demo token — no redemption value'}</div></div></div>)}</div><div className="field"><label htmlFor="allocation">Allocate per asset</label><input id="allocation" type="text" inputMode="decimal" value={allocation} onChange={e=>setAllocation(e.target.value)}/><span className="hint">10–1,000,000 units per asset, subject to funding and numerical limits.</span></div><button className="button full" onClick={()=>setStep(1)} disabled={!/^\d+$/.test(allocation)||BigInt(allocation||'0')<10n||BigInt(allocation||'0')>1000000n}>Choose concentration</button></>}
 {step===1&&<><h2>Choose a profile.</h2><div className={styles.presets}>{presets.map((p,i)=><button key={p.name} className={styles.preset} aria-pressed={i===preset} onClick={()=>setPreset(i)}><strong>{p.name}</strong><span>{p.description}</span></button>)}</div><div className="field"><label htmlFor="fee">Swap fee</label><select id="fee" value={fee} onChange={e=>setFee(e.target.value)}><option value="100">0.01%</option><option value="500">0.05%</option><option value="1000">0.10%</option></select></div><button className="button full" onClick={()=>setStep(2)}>Review strategy</button></>}
 {step===2&&<><h2>Review your intent.</h2><div className="stack"><div className="row"><span>Per asset</span><strong>{allocation} units</strong></div><div className="row"><span>Concentration</span><strong>{choice.name}</strong></div><div className="row"><span>Fee</span><strong>{fee==='500'?'0.05%':fee==='100'?'0.01%':'0.10%'}</strong></div><p className="notice">The next step computes quantized radii and exact token allocations. Aqua allowances are bounded at four times the initial allocation. Each transaction is simulated and reviewed separately.</p><label className={styles.check}><input type="checkbox" checked={shared} onChange={e=>setShared(e.target.checked)}/>I understand that other wallet activity can make this allocation unavailable.</label><label className={styles.check}><input type="checkbox" checked={risk} onChange={e=>setRisk(e.target.checked)}/>I understand that a depeg can change the tokens and value I hold.</label><button className="button full" disabled={!risk||!shared||publication.busy||(!publication.ready&&publication.connected&&!publication.wrongChain)} onClick={()=>{if(!publication.connected){publication.connect();return;}if(publication.wrongChain){void publication.switchNetwork?.();return;}publication.start({allocation,preset:choice.name as StrategyProfileInput["preset"],feePpm:Number(fee) as StrategyProfileInput["feePpm"]});}}>{!publication.connected?'Connect wallet':publication.wrongChain?'Switch network':publication.busy?'Preparing configuration…':'Prepare publication'}</button>{publication.error&&<p className="notice" role="alert">{publication.error}</p>}</div></>}
 {step===3&&<><h2>Publish from your wallet.</h2>{publication.restored&&<p className="notice">Saved publication restored. Completed onchain steps are checked before the next review.</p>}{publication.view&&<><p>{publication.network} · Maker nonce {publication.view.nonce}</p><dl className="stack">{publication.view.allocations.map(t=><div key={t.symbol}><dt>{t.symbol}</dt><dd>{t.amount} allocated · {t.cap} Aqua approval target (if needed)</dd></div>)}</dl><details><summary>Quantized curve configuration</summary><p className="mono">{publication.view.hash}</p><ol>{publication.view.ticks.map(t=><li key={t.key}><p>{t.share}% · Realized reference threshold: {t.threshold}</p><p className="mono">Key: {t.key}<br/>Radius: {t.radius}</p></li>)}</ol></details></>}{publication.error&&<p className="notice">{publication.error}</p>}{publication.active&&!publication.admin.pending?<div className="stack"><p className="notice">Strategy is active. The index will show its receipt shortly.</p><Link className="button full" href={`/liquidity/${publication.view!.hash}`}>View strategy</Link><button className="button secondary" onClick={()=>{publication.newDraft();setStep(0);}}>Create another strategy</button></div>:<><StrategyAdminView state={publication.admin} publication/><button className="button secondary" disabled={publication.busy||publication.admin.busy||!!publication.admin.pending} onClick={publication.editDraft}>Edit unshipped configuration</button></>}</>}
 {step>0&&!publication.draft&&<button className={styles.backButton} onClick={()=>setStep(step-1)}>← Back</button>}</div><aside className={styles.preview}><div className={styles.rings} aria-hidden="true"><i/><i/><i/></div><h3>{choice.name}</h3><p className="hint">Initial funded principal allocation</p>{choice.shares.map((share,i)=><div className={styles.share} key={i}><span>{choice.thresholds[i]}</span><strong>{share}%</strong></div>)}<p className="hint" style={{marginTop:24}}>Reference thresholds describe a single-coin depeg scenario. Actual quantized thresholds are shown only after certified configuration. They are not guaranteed price floors.</p></aside></div></section>;
}
