'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useWallet} from '../wallet/WalletProvider';
import {useDeployment} from './api';
import {presets} from '../content';
import styles from './Liquidity.module.css';
export {default as Liquidity} from './Strategies';
export function NewStrategy(){
 const [step,setStep]=useState(0),[allocation,setAllocation]=useState('10'),[preset,setPreset]=useState(1),[fee,setFee]=useState('500'),[risk,setRisk]=useState(false),[shared,setShared]=useState(false);
 const deployment=useDeployment(),wallet=useWallet();const choice=presets[preset]!;
 return <section className="page"><Link href="/liquidity" className={styles.back}>← Your liquidity</Link><div className="page-head"><div><div className="eyebrow">Build a strategy</div><h1>Find your concentration.</h1><p>One wallet. Three assets. Your choice of exposure.</p></div></div><ol className={styles.steps}>{['Assets','Concentration','Review','Publish'].map((name,i)=><li key={name} aria-current={step===i?'step':undefined}><span>{i+1}</span>{name}</li>)}</ol>
 <div className={styles.wizard}><div className="panel">
 {step===0&&<><h2>Start with your assets.</h2><p className="hint">Equal initial amounts of each asset. Your tokens stay in your wallet.</p><div className={styles.assets}>{['USDC','oUSD6','oUSD18'].map((s,i)=><div className="row" key={s}><span className={styles.assetDot}>{i===0?'$':i===1?'6':'18'}</span><div><strong>{s}</strong><div className="hint">{i===0?'Arc testnet USDC':'Demo token — no redemption value'}</div></div></div>)}</div><div className="field"><label htmlFor="allocation">Allocate per asset</label><input id="allocation" type="text" inputMode="decimal" value={allocation} onChange={e=>setAllocation(e.target.value)}/><span className="hint">10–1,000,000 units per asset, subject to funding and numerical limits.</span></div><button className="button full" onClick={()=>setStep(1)} disabled={!/^\d+$/.test(allocation)||BigInt(allocation||'0')<10n||BigInt(allocation||'0')>1000000n}>Choose concentration</button></>}
 {step===1&&<><h2>Choose a profile.</h2><div className={styles.presets}>{presets.map((p,i)=><button key={p.name} className={styles.preset} aria-pressed={i===preset} onClick={()=>setPreset(i)}><strong>{p.name}</strong><span>{p.description}</span></button>)}</div><div className="field"><label htmlFor="fee">Swap fee</label><select id="fee" value={fee} onChange={e=>setFee(e.target.value)}><option value="100">0.01%</option><option value="500">0.05%</option><option value="1000">0.10%</option></select></div><button className="button full" onClick={()=>setStep(2)}>Review strategy</button></>}
 {step===2&&<><h2>Review your intent.</h2><div className="stack"><div className="row"><span>Per asset</span><strong>{allocation} units</strong></div><div className="row"><span>Concentration</span><strong>{choice.name}</strong></div><div className="row"><span>Fee</span><strong>{fee==='500'?'0.05%':fee==='100'?'0.01%':'0.10%'}</strong></div><p className="notice">This is a parameter preview. Certified radii, exact token allocations, approval caps and gas must be available before publication.</p><label className={styles.check}><input type="checkbox" checked={shared} onChange={e=>setShared(e.target.checked)}/>I understand that other wallet activity can make this allocation unavailable.</label><label className={styles.check}><input type="checkbox" checked={risk} onChange={e=>setRisk(e.target.checked)}/>I understand that a depeg can change the tokens and value I hold.</label><button className="button full" disabled={!risk||!shared} onClick={()=>setStep(3)}>Continue to publication</button></div></>}
 {step===3&&<><h2>Publish from your wallet.</h2><p>Approve assets → publish allocation → activate strategy.</p><div className="notice">{deployment.error?.message??'Certified publication is not available in this build.'}</div><button style={{marginTop:24}} className="button full" disabled={wallet.connected} onClick={wallet.connect}>{wallet.connected?'Publication unavailable':'Connect wallet'}</button></>}
 {step>0&&<button className={styles.backButton} onClick={()=>setStep(step-1)}>← Back</button>}</div><aside className={styles.preview}><div className={styles.rings} aria-hidden="true"><i/><i/><i/></div><h3>{choice.name}</h3><p className="hint">Initial funded principal allocation</p>{choice.shares.map((share,i)=><div className={styles.share} key={i}><span>{choice.thresholds[i]}</span><strong>{share}%</strong></div>)}<p className="hint" style={{marginTop:24}}>Reference thresholds describe a single-coin depeg scenario. Actual quantized thresholds are shown only after certified configuration. They are not guaranteed price floors.</p></aside></div></section>;
}
